"""
    Zulip REST API

    Powerful open source group chat   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bad_event_queue_id_error_all_of import BadEventQueueIdErrorAllOf
from openapi_client.model.coded_error_base import CodedErrorBase
globals()['BadEventQueueIdErrorAllOf'] = BadEventQueueIdErrorAllOf
globals()['CodedErrorBase'] = CodedErrorBase
from openapi_client.model.bad_event_queue_id_error import BadEventQueueIdError


class TestBadEventQueueIdError(unittest.TestCase):
    """BadEventQueueIdError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadEventQueueIdError(self):
        """Test BadEventQueueIdError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BadEventQueueIdError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
