"""
    Zulip REST API

    Powerful open source group chat   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.messages_api import MessagesApi  # noqa: E501


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_reaction(self):
        """Test case for add_reaction

        Add an emoji reaction  # noqa: E501
        """
        pass

    def test_check_messages_match_narrow(self):
        """Test case for check_messages_match_narrow

        Check if messages match a narrow  # noqa: E501
        """
        pass

    def test_delete_message(self):
        """Test case for delete_message

        Delete a message  # noqa: E501
        """
        pass

    def test_get_file_temporary_url(self):
        """Test case for get_file_temporary_url

        Get public temporary URL  # noqa: E501
        """
        pass

    def test_get_message_history(self):
        """Test case for get_message_history

        Get a message's edit history  # noqa: E501
        """
        pass

    def test_get_messages(self):
        """Test case for get_messages

        Get messages  # noqa: E501
        """
        pass

    def test_get_raw_message(self):
        """Test case for get_raw_message

        Get a message's raw Markdown  # noqa: E501
        """
        pass

    def test_mark_all_as_read(self):
        """Test case for mark_all_as_read

        Mark all messages as read  # noqa: E501
        """
        pass

    def test_mark_stream_as_read(self):
        """Test case for mark_stream_as_read

        Mark messages in a stream as read  # noqa: E501
        """
        pass

    def test_mark_topic_as_read(self):
        """Test case for mark_topic_as_read

        Mark messages in a topic as read  # noqa: E501
        """
        pass

    def test_remove_reaction(self):
        """Test case for remove_reaction

        Remove an emoji reaction  # noqa: E501
        """
        pass

    def test_render_message(self):
        """Test case for render_message

        Render message  # noqa: E501
        """
        pass

    def test_send_message(self):
        """Test case for send_message

        Send a message  # noqa: E501
        """
        pass

    def test_update_message(self):
        """Test case for update_message

        Edit a message  # noqa: E501
        """
        pass

    def test_update_message_flags(self):
        """Test case for update_message_flags

        Update personal message flags  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        Upload a file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
