/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZulipRestApi);
  }
}(this, function(expect, ZulipRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZulipRestApi.EmojiReactionAllOf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmojiReactionAllOf', function() {
    it('should create an instance of EmojiReactionAllOf', function() {
      // uncomment below and update the code to test EmojiReactionAllOf
      //var instane = new ZulipRestApi.EmojiReactionAllOf();
      //expect(instance).to.be.a(ZulipRestApi.EmojiReactionAllOf);
    });

    it('should have the property emojiCode (base name: "emoji_code")', function() {
      // uncomment below and update the code to test the property emojiCode
      //var instance = new ZulipRestApi.EmojiReactionAllOf();
      //expect(instance).to.be();
    });

    it('should have the property emojiName (base name: "emoji_name")', function() {
      // uncomment below and update the code to test the property emojiName
      //var instance = new ZulipRestApi.EmojiReactionAllOf();
      //expect(instance).to.be();
    });

    it('should have the property reactionType (base name: "reaction_type")', function() {
      // uncomment below and update the code to test the property reactionType
      //var instance = new ZulipRestApi.EmojiReactionAllOf();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new ZulipRestApi.EmojiReactionAllOf();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new ZulipRestApi.EmojiReactionAllOf();
      //expect(instance).to.be();
    });

  });

}));
