# Zulip REST API
#
# Powerful open source group chat 
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ApiKeyResponse
#'
#' @description ApiKeyResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field result  \link{AnyType} 
#'
#' @field msg  \link{AnyType} 
#'
#' @field api_key  character 
#'
#' @field email  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApiKeyResponse <- R6::R6Class(
  'ApiKeyResponse',
  public = list(
    `result` = NULL,
    `msg` = NULL,
    `api_key` = NULL,
    `email` = NULL,
    initialize = function(
        `result`, `msg`, `api_key`, `email`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`result`)) {
        stopifnot(R6::is.R6(`result`))
        self$`result` <- `result`
      }
      if (!missing(`msg`)) {
        stopifnot(R6::is.R6(`msg`))
        self$`msg` <- `msg`
      }
      if (!missing(`api_key`)) {
        stopifnot(is.character(`api_key`), length(`api_key`) == 1)
        self$`api_key` <- `api_key`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
    },
    toJSON = function() {
      ApiKeyResponseObject <- list()
      if (!is.null(self$`result`)) {
        ApiKeyResponseObject[['result']] <-
          self$`result`$toJSON()
      }
      if (!is.null(self$`msg`)) {
        ApiKeyResponseObject[['msg']] <-
          self$`msg`$toJSON()
      }
      if (!is.null(self$`api_key`)) {
        ApiKeyResponseObject[['api_key']] <-
          self$`api_key`
      }
      if (!is.null(self$`email`)) {
        ApiKeyResponseObject[['email']] <-
          self$`email`
      }

      ApiKeyResponseObject
    },
    fromJSON = function(ApiKeyResponseJson) {
      ApiKeyResponseObject <- jsonlite::fromJSON(ApiKeyResponseJson)
      if (!is.null(ApiKeyResponseObject$`result`)) {
        resultObject <- AnyType$new()
        resultObject$fromJSON(jsonlite::toJSON(ApiKeyResponseObject$result, auto_unbox = TRUE, digits = NA))
        self$`result` <- resultObject
      }
      if (!is.null(ApiKeyResponseObject$`msg`)) {
        msgObject <- AnyType$new()
        msgObject$fromJSON(jsonlite::toJSON(ApiKeyResponseObject$msg, auto_unbox = TRUE, digits = NA))
        self$`msg` <- msgObject
      }
      if (!is.null(ApiKeyResponseObject$`api_key`)) {
        self$`api_key` <- ApiKeyResponseObject$`api_key`
      }
      if (!is.null(ApiKeyResponseObject$`email`)) {
        self$`email` <- ApiKeyResponseObject$`email`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`result`)) {
        sprintf(
        '"result":
        %s
        ',
        jsonlite::toJSON(self$`result`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`msg`)) {
        sprintf(
        '"msg":
        %s
        ',
        jsonlite::toJSON(self$`msg`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`api_key`)) {
        sprintf(
        '"api_key":
          "%s"
                ',
        self$`api_key`
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ApiKeyResponseJson) {
      ApiKeyResponseObject <- jsonlite::fromJSON(ApiKeyResponseJson)
      self$`result` <- AnyType$new()$fromJSON(jsonlite::toJSON(ApiKeyResponseObject$result, auto_unbox = TRUE, digits = NA))
      self$`msg` <- AnyType$new()$fromJSON(jsonlite::toJSON(ApiKeyResponseObject$msg, auto_unbox = TRUE, digits = NA))
      self$`api_key` <- ApiKeyResponseObject$`api_key`
      self$`email` <- ApiKeyResponseObject$`email`
      self
    }
  )
)
