# Zulip REST API
#
# Powerful open source group chat 
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Draft
#'
#' @description Draft Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  integer [optional]
#'
#' @field type  character 
#'
#' @field to  list( integer ) 
#'
#' @field topic  character 
#'
#' @field content  character 
#'
#' @field timestamp  numeric [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Draft <- R6::R6Class(
  'Draft',
  public = list(
    `id` = NULL,
    `type` = NULL,
    `to` = NULL,
    `topic` = NULL,
    `content` = NULL,
    `timestamp` = NULL,
    initialize = function(
        `type`, `to`, `topic`, `content`, `id`=NULL, `timestamp`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`to`)) {
        stopifnot(is.vector(`to`), length(`to`) != 0)
        sapply(`to`, function(x) stopifnot(is.character(x)))
        self$`to` <- `to`
      }
      if (!missing(`topic`)) {
        stopifnot(is.character(`topic`), length(`topic`) == 1)
        self$`topic` <- `topic`
      }
      if (!missing(`content`)) {
        stopifnot(is.character(`content`), length(`content`) == 1)
        self$`content` <- `content`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`timestamp`)) {
        self$`timestamp` <- `timestamp`
      }
    },
    toJSON = function() {
      DraftObject <- list()
      if (!is.null(self$`id`)) {
        DraftObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`type`)) {
        DraftObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`to`)) {
        DraftObject[['to']] <-
          self$`to`
      }
      if (!is.null(self$`topic`)) {
        DraftObject[['topic']] <-
          self$`topic`
      }
      if (!is.null(self$`content`)) {
        DraftObject[['content']] <-
          self$`content`
      }
      if (!is.null(self$`timestamp`)) {
        DraftObject[['timestamp']] <-
          self$`timestamp`
      }

      DraftObject
    },
    fromJSON = function(DraftJson) {
      DraftObject <- jsonlite::fromJSON(DraftJson)
      if (!is.null(DraftObject$`id`)) {
        self$`id` <- DraftObject$`id`
      }
      if (!is.null(DraftObject$`type`)) {
        self$`type` <- DraftObject$`type`
      }
      if (!is.null(DraftObject$`to`)) {
        self$`to` <- ApiClient$new()$deserializeObj(DraftObject$`to`, "array[integer]", loadNamespace("openapi"))
      }
      if (!is.null(DraftObject$`topic`)) {
        self$`topic` <- DraftObject$`topic`
      }
      if (!is.null(DraftObject$`content`)) {
        self$`content` <- DraftObject$`content`
      }
      if (!is.null(DraftObject$`timestamp`)) {
        self$`timestamp` <- DraftObject$`timestamp`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`to`)) {
        sprintf(
        '"to":
           [%s]
        ',
        paste(unlist(lapply(self$`to`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`topic`)) {
        sprintf(
        '"topic":
          "%s"
                ',
        self$`topic`
        )},
        if (!is.null(self$`content`)) {
        sprintf(
        '"content":
          "%s"
                ',
        self$`content`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DraftJson) {
      DraftObject <- jsonlite::fromJSON(DraftJson)
      self$`id` <- DraftObject$`id`
      self$`type` <- DraftObject$`type`
      self$`to` <- ApiClient$new()$deserializeObj(DraftObject$`to`, "array[integer]", loadNamespace("openapi"))
      self$`topic` <- DraftObject$`topic`
      self$`content` <- DraftObject$`content`
      self$`timestamp` <- DraftObject$`timestamp`
      self
    }
  )
)
