# Zulip REST API
#
# Powerful open source group chat 
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EmojiReactionBaseUser
#'
#' @description EmojiReactionBaseUser Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  integer [optional]
#'
#' @field email  character [optional]
#'
#' @field full_name  character [optional]
#'
#' @field is_mirror_dummy  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EmojiReactionBaseUser <- R6::R6Class(
  'EmojiReactionBaseUser',
  public = list(
    `id` = NULL,
    `email` = NULL,
    `full_name` = NULL,
    `is_mirror_dummy` = NULL,
    initialize = function(
        `id`=NULL, `email`=NULL, `full_name`=NULL, `is_mirror_dummy`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!is.null(`full_name`)) {
        stopifnot(is.character(`full_name`), length(`full_name`) == 1)
        self$`full_name` <- `full_name`
      }
      if (!is.null(`is_mirror_dummy`)) {
        stopifnot(is.logical(`is_mirror_dummy`), length(`is_mirror_dummy`) == 1)
        self$`is_mirror_dummy` <- `is_mirror_dummy`
      }
    },
    toJSON = function() {
      EmojiReactionBaseUserObject <- list()
      if (!is.null(self$`id`)) {
        EmojiReactionBaseUserObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`email`)) {
        EmojiReactionBaseUserObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`full_name`)) {
        EmojiReactionBaseUserObject[['full_name']] <-
          self$`full_name`
      }
      if (!is.null(self$`is_mirror_dummy`)) {
        EmojiReactionBaseUserObject[['is_mirror_dummy']] <-
          self$`is_mirror_dummy`
      }

      EmojiReactionBaseUserObject
    },
    fromJSON = function(EmojiReactionBaseUserJson) {
      EmojiReactionBaseUserObject <- jsonlite::fromJSON(EmojiReactionBaseUserJson)
      if (!is.null(EmojiReactionBaseUserObject$`id`)) {
        self$`id` <- EmojiReactionBaseUserObject$`id`
      }
      if (!is.null(EmojiReactionBaseUserObject$`email`)) {
        self$`email` <- EmojiReactionBaseUserObject$`email`
      }
      if (!is.null(EmojiReactionBaseUserObject$`full_name`)) {
        self$`full_name` <- EmojiReactionBaseUserObject$`full_name`
      }
      if (!is.null(EmojiReactionBaseUserObject$`is_mirror_dummy`)) {
        self$`is_mirror_dummy` <- EmojiReactionBaseUserObject$`is_mirror_dummy`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`full_name`)) {
        sprintf(
        '"full_name":
          "%s"
                ',
        self$`full_name`
        )},
        if (!is.null(self$`is_mirror_dummy`)) {
        sprintf(
        '"is_mirror_dummy":
          %s
                ',
        tolower(self$`is_mirror_dummy`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EmojiReactionBaseUserJson) {
      EmojiReactionBaseUserObject <- jsonlite::fromJSON(EmojiReactionBaseUserJson)
      self$`id` <- EmojiReactionBaseUserObject$`id`
      self$`email` <- EmojiReactionBaseUserObject$`email`
      self$`full_name` <- EmojiReactionBaseUserObject$`full_name`
      self$`is_mirror_dummy` <- EmojiReactionBaseUserObject$`is_mirror_dummy`
      self
    }
  )
)
