# Zulip REST API
#
# Powerful open source group chat 
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EmojiBase
#'
#' @description EmojiBase Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field emoji_code  character [optional]
#'
#' @field emoji_name  character [optional]
#'
#' @field reaction_type  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EmojiBase <- R6::R6Class(
  'EmojiBase',
  public = list(
    `emoji_code` = NULL,
    `emoji_name` = NULL,
    `reaction_type` = NULL,
    initialize = function(
        `emoji_code`=NULL, `emoji_name`=NULL, `reaction_type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`emoji_code`)) {
        stopifnot(is.character(`emoji_code`), length(`emoji_code`) == 1)
        self$`emoji_code` <- `emoji_code`
      }
      if (!is.null(`emoji_name`)) {
        stopifnot(is.character(`emoji_name`), length(`emoji_name`) == 1)
        self$`emoji_name` <- `emoji_name`
      }
      if (!is.null(`reaction_type`)) {
        stopifnot(is.character(`reaction_type`), length(`reaction_type`) == 1)
        self$`reaction_type` <- `reaction_type`
      }
    },
    toJSON = function() {
      EmojiBaseObject <- list()
      if (!is.null(self$`emoji_code`)) {
        EmojiBaseObject[['emoji_code']] <-
          self$`emoji_code`
      }
      if (!is.null(self$`emoji_name`)) {
        EmojiBaseObject[['emoji_name']] <-
          self$`emoji_name`
      }
      if (!is.null(self$`reaction_type`)) {
        EmojiBaseObject[['reaction_type']] <-
          self$`reaction_type`
      }

      EmojiBaseObject
    },
    fromJSON = function(EmojiBaseJson) {
      EmojiBaseObject <- jsonlite::fromJSON(EmojiBaseJson)
      if (!is.null(EmojiBaseObject$`emoji_code`)) {
        self$`emoji_code` <- EmojiBaseObject$`emoji_code`
      }
      if (!is.null(EmojiBaseObject$`emoji_name`)) {
        self$`emoji_name` <- EmojiBaseObject$`emoji_name`
      }
      if (!is.null(EmojiBaseObject$`reaction_type`)) {
        self$`reaction_type` <- EmojiBaseObject$`reaction_type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`emoji_code`)) {
        sprintf(
        '"emoji_code":
          "%s"
                ',
        self$`emoji_code`
        )},
        if (!is.null(self$`emoji_name`)) {
        sprintf(
        '"emoji_name":
          "%s"
                ',
        self$`emoji_name`
        )},
        if (!is.null(self$`reaction_type`)) {
        sprintf(
        '"reaction_type":
          "%s"
                ',
        self$`reaction_type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EmojiBaseJson) {
      EmojiBaseObject <- jsonlite::fromJSON(EmojiBaseJson)
      self$`emoji_code` <- EmojiBaseObject$`emoji_code`
      self$`emoji_name` <- EmojiBaseObject$`emoji_name`
      self$`reaction_type` <- EmojiBaseObject$`reaction_type`
      self
    }
  )
)
