# Zulip REST API
#
# Powerful open source group chat 
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Messages operations
#' @description openapi.Messages
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ AddReaction } \emph{ Add an emoji reaction }
#' Add an [emoji reaction](/help/emoji-reactions) to a message.  &#x60;POST {{ api_url }}/v1/messages/{message_id}/reactions&#x60; 
#'
#' \itemize{
#' \item \emph{ @param } message.id integer
#' \item \emph{ @param } emoji.name character
#' \item \emph{ @param } emoji.code character
#' \item \emph{ @param } reaction.type character
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : CodedError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ CheckMessagesMatchNarrow } \emph{ Check if messages match a narrow }
#' Check whether a set of messages match a [narrow](/api/construct-narrow).  &#x60;GET {{ api_url }}/v1/messages/matches_narrow&#x60;  For many common narrows (E.g. a topic), clients can write an efficient client-side check to determine whether a newly arrived message belongs in the view.  This endpoint is designed to allow clients to handle more complex narrows for which the client does not (or in the case of full-text search, cannot) implement this check.  The format of the &#x60;match_subject&#x60; and &#x60;match_content&#x60; objects is designed to match those of &#x60;GET /messages&#x60;, so that a client can splice these fields into a &#x60;message&#x60; object received from &#x60;GET /events&#x60; and end up with an extended message object identical to how a &#x60;GET /messages&#x60; for the current narrow would have returned the message. 
#'
#' \itemize{
#' \item \emph{ @param } msg.ids list( integer )
#' \item \emph{ @param } narrow list( object )
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteMessage } \emph{ Delete a message }
#' Permanently delete a message.  &#x60;DELETE {{ api_url }}/v1/messages/{msg_id}&#x60;  This API corresponds to the [delete a message completely][delete-completely] feature documented in the Zulip Help Center.  [delete-completely]: /help/edit-or-delete-a-message#delete-a-message-completely 
#'
#' \itemize{
#' \item \emph{ @param } message.id integer
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : OneOfobjectobject 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetFileTemporaryUrl } \emph{ Get public temporary URL }
#' Get a temporary URL for access to the file that doesn&#39;t require authentication. 
#'
#' \itemize{
#' \item \emph{ @param } realm.id.str integer
#' \item \emph{ @param } filename character
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetMessageHistory } \emph{ Get a message&#39;s edit history }
#' Fetch the message edit history of a previously edited message.  &#x60;GET {{ api_url }}/v1/messages/{message_id}/history&#x60;  Note that edit history may be disabled in some organizations; see the [Zulip Help Center documentation on editing messages][edit-settings].  [edit-settings]: /help/view-a-messages-edit-history 
#'
#' \itemize{
#' \item \emph{ @param } message.id integer
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : InvalidMessageError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetMessages } \emph{ Get messages }
#' Fetch message history from a Zulip server.  &#x60;GET {{ api_url }}/v1/messages&#x60;  This &#x60;GET /api/v1/messages&#x60; endpoint is the primary way to fetch message history from a Zulip server.  It is useful both for Zulip clients (e.g. the web, desktop, mobile, and terminal clients) as well as bots, API clients, backup scripts, etc.  By specifying a [narrow filter](/api/construct-narrow), you can use this endpoint to fetch the messages matching any search query that is supported by Zulip&#39;s powerful full-text search backend.  When a narrow is not specified, it can be used to fetch a user&#39;s message history. (We recommend paginating to 1000 messages at a time.)  In either case, you specify an &#x60;anchor&#x60; message (or ask the server to calculate the first unread message for you and use that as the anchor), as well as a number of messages before and after the anchor message.  The server returns those messages, sorted by message ID, as well as some metadata that makes it easy for a client to determine whether there are more messages matching the query that were not returned due to the &#x60;num_before&#x60; and &#x60;num_after&#x60; limits.  We recommend using &#x60;num_before &lt;&#x3D; 1000&#x60; and &#x60;num_after &lt;&#x3D; 1000&#x60; to avoid generating very large HTTP responses. A maximum of 5000 messages can be obtained per request; attempting to exceed this will result in an error. 
#'
#' \itemize{
#' \item \emph{ @param } num.before integer
#' \item \emph{ @param } num.after integer
#' \item \emph{ @param } anchor \link{OneOfstringinteger}
#' \item \emph{ @param } narrow list( object )
#' \item \emph{ @param } client.gravatar character
#' \item \emph{ @param } apply.markdown character
#' \item \emph{ @param } use.first.unread.anchor character
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetRawMessage } \emph{ Get a message&#39;s raw Markdown }
#' Get the raw content of a message.  &#x60;GET {{ api_url }}/v1/messages/{msg_id}&#x60;  This is a rarely-used endpoint relevant for clients that primarily work with HTML-rendered messages but might need to occasionally fetch the message&#39;s raw Markdown (e.g. for pre-filling a message-editing UI). 
#'
#' \itemize{
#' \item \emph{ @param } message.id integer
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : InvalidMessageError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarkAllAsRead } \emph{ Mark all messages as read }
#' Marks all of the current user&#39;s unread messages as read.  &#x60;POST {{ api_url }}/v1/mark_all_as_read&#x60; 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarkStreamAsRead } \emph{ Mark messages in a stream as read }
#' Mark all the unread messages in a stream as read. 
#'
#' \itemize{
#' \item \emph{ @param } stream.id integer
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarkTopicAsRead } \emph{ Mark messages in a topic as read }
#' Mark all the unread messages in a topic as read. 
#'
#' \itemize{
#' \item \emph{ @param } stream.id integer
#' \item \emph{ @param } topic.name character
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RemoveReaction } \emph{ Remove an emoji reaction }
#' Remove an [emoji reaction](/help/emoji-reactions) from a message.  &#x60;DELETE {{ api_url }}/v1/messages/{message_id}/reactions&#x60; 
#'
#' \itemize{
#' \item \emph{ @param } message.id integer
#' \item \emph{ @param } emoji.name character
#' \item \emph{ @param } emoji.code character
#' \item \emph{ @param } reaction.type character
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : CodedError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RenderMessage } \emph{ Render message }
#' Render a message to HTML.  &#x60;POST {{ api_url }}/v1/messages/render&#x60; 
#'
#' \itemize{
#' \item \emph{ @param } content character
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ SendMessage } \emph{ Send a message }
#' Send a stream or a private message.  &#x60;POST {{ api_url }}/v1/messages&#x60; 
#'
#' \itemize{
#' \item \emph{ @param } type Enum < [private, stream] > 
#' \item \emph{ @param } to list( integer )
#' \item \emph{ @param } content character
#' \item \emph{ @param } topic character
#' \item \emph{ @param } queue.id character
#' \item \emph{ @param } local.id character
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : OneOfobjectobject 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateMessage } \emph{ Edit a message }
#' Edit/update the content or topic of a message.  &#x60;PATCH {{ api_url }}/v1/messages/{msg_id}&#x60;  &#x60;{msg_id}&#x60; in the above URL should be replaced with the ID of the message you wish you update.  You can [resolve topics](/help/resolve-a-topic) by editing the topic to &#x60;✔ {original_topic}&#x60;.  **Note**: See [configuring message editing][config-message-editing] for detailed documentation on when users are allowed to edit topics.  [config-message-editing]: /help/configure-message-editing-and-deletion 
#'
#' \itemize{
#' \item \emph{ @param } message.id integer
#' \item \emph{ @param } topic character
#' \item \emph{ @param } propagate.mode Enum < [change_one, change_later, change_all] > 
#' \item \emph{ @param } send.notification.to.old.thread character
#' \item \emph{ @param } send.notification.to.new.thread character
#' \item \emph{ @param } content character
#' \item \emph{ @param } stream.id integer
#' \item \emph{ @returnType } \link{JsonSuccess} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccess 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : CodedError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateMessageFlags } \emph{ Update personal message flags }
#' Add or remove personal message flags like &#x60;read&#x60; and &#x60;starred&#x60; on a collection of message IDs.  &#x60;POST {{ api_url }}/v1/messages/flags&#x60;  For updating the &#x60;read&#x60; flag on common collections of messages, see also the [special endpoints for marking message as read in bulk](/api/mark-all-as-read). 
#'
#' \itemize{
#' \item \emph{ @param } messages list( integer )
#' \item \emph{ @param } op Enum < [add, remove] > 
#' \item \emph{ @param } flag character
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UploadFile } \emph{ Upload a file }
#' Upload a single file and get the corresponding URI.  &#x60;POST {{ api_url }}/v1/user_uploads&#x60;  Initially, only you will be able to access the link.  To share the uploaded file, you&#39;ll need to [send a message][send-message] containing the resulting link.  Users who can already access the link can reshare it with other users by sending additional Zulip messages containing the link.  [uploaded-files]: /help/manage-your-uploaded-files [send-message]: /api/send-message 
#'
#' \itemize{
#' \item \emph{ @param } filename data.frame
#' \item \emph{ @returnType } \link{JsonSuccessBase} \cr
#'
#'
#' \item status code : 200 | Success.
#'
#' \item return type : JsonSuccessBase 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  AddReaction  ####################
#'
#' library(openapi)
#' var.message.id <- 42 # integer | The target message's ID. 
#' var.emoji.name <- 'octopus' # character | The target emoji's human-readable name.  To find an emoji's name, hover over a message to reveal three icons on the right, then click the smiley face icon. Images of available reaction emojis appear. Hover over the emoji you want, and note that emoji's text name. 
#' var.emoji.code <- '1f419' # character | A unique identifier, defining the specific emoji codepoint requested, within the namespace of the `reaction_type`.  For most API clients, you won't need this, but it's important for Zulip apps to handle rare corner cases when adding/removing votes on an emoji reaction added previously by another user.  If the existing reaction was added when the Zulip server was using a previous version of the emoji data mapping between Unicode codepoints and human-readable names, sending the `emoji_code` in the data for the original reaction allows the Zulip server to correctly interpret your upvote as an upvote rather than a reaction with a \"diffenent\" emoji. 
#' var.reaction.type <- 'unicode_emoji' # character | If an app is adding/removing a vote on an existing reaction, it should pass this parameter using the value the server provided for the existing reaction for specificity.  Supported values:  * `unicode_emoji`: Unicode emoji (`emoji_code` will be its Unicode codepoint). * `realm_emoji`: Custom emoji. (`emoji_code` will be its ID). * `zulip_extra_emoji`: Special emoji included with Zulip.  Exists to    namespace the `zulip` emoji.  **Changes**: In Zulip 3.0 (feature level 2), this become optional for [custom emoji](/help/add-custom-emoji); previously, this endpoint assumed `unicode_emoji` if this parameter was not specified. 
#'
#' #Add an emoji reaction
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$AddReaction(var.message.id, var.emoji.name, emoji.code=var.emoji.code, reaction.type=var.reaction.type)
#'
#'
#' ####################  CheckMessagesMatchNarrow  ####################
#'
#' library(openapi)
#' var.msg.ids <- [56] # array[integer] | List of IDs for the messages to check.
#' var.narrow <- NULL # array[object] | A structure defining the narrow to check against. See how to [construct a narrow](/api/construct-narrow).
#'
#' #Check if messages match a narrow
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$CheckMessagesMatchNarrow(var.msg.ids, var.narrow)
#'
#'
#' ####################  DeleteMessage  ####################
#'
#' library(openapi)
#' var.message.id <- 42 # integer | The target message's ID. 
#'
#' #Delete a message
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$DeleteMessage(var.message.id)
#'
#'
#' ####################  GetFileTemporaryUrl  ####################
#'
#' library(openapi)
#' var.realm.id.str <- 1 # integer | The realm id. 
#' var.filename <- '4e/m2A3MSqFnWRLUf9SaPzQ0Up_/zulip.txt' # character | Path to the URL. 
#'
#' #Get public temporary URL
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$GetFileTemporaryUrl(var.realm.id.str, var.filename)
#'
#'
#' ####################  GetMessageHistory  ####################
#'
#' library(openapi)
#' var.message.id <- 42 # integer | The target message's ID. 
#'
#' #Get a message's edit history
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$GetMessageHistory(var.message.id)
#'
#'
#' ####################  GetMessages  ####################
#'
#' library(openapi)
#' var.num.before <- 4 # integer | The number of messages with IDs less than the anchor to retrieve. 
#' var.num.after <- 8 # integer | The number of messages with IDs greater than the anchor to retrieve. 
#' var.anchor <- OneOfstringinteger$new() # OneOfstringinteger | Integer message ID to anchor fetching of new messages. Supports special string values for when the client wants the server to compute the anchor to use:  * `newest`: The most recent message. * `oldest`: The oldest message. * `first_unread`: The oldest unread message matching the   query, if any; otherwise, the most recent message.  The special values of `'newest'` and `'oldest'` are also supported for anchoring the query at the most recent or oldest messages.  **Changes**: String values are new in Zulip 3.0 (feature level 1).  The   `first_unread` functionality was supported in Zulip 2.1.x   and older by not sending anchor and using use_first_unread_anchor.    In Zulip 2.1.x and older, `oldest` can be emulated with   `anchor=0`, and `newest` with `anchor=10000000000000000`   (that specific large value works around a bug in Zulip   2.1.x and older in the `found_newest` return value). 
#' var.narrow <- [] # array[object] | The narrow where you want to fetch the messages from. See how to [construct a narrow](/api/construct-narrow). 
#' var.client.gravatar <- FALSE # character | Whether the client supports computing gravatars URLs.  If enabled, `avatar_url` will be included in the response only if there is a Zulip avatar, and will be `null` for users who are using gravatar as their avatar.  This option significantly reduces the compressed size of user data, since gravatar URLs are long, random strings and thus do not compress well. The `client_gravatar` field is set to `true` if clients can compute their own gravatars. 
#' var.apply.markdown <- TRUE # character | If `true`, message content is returned in the rendered HTML format. If `false`, message content is returned in the raw Markdown-format text that user entered. 
#' var.use.first.unread.anchor <- FALSE # character | Legacy way to specify `anchor=\"first_unread\"` in Zulip 2.1.x and older.  Whether to use the (computed by the server) first unread message matching the narrow as the `anchor`.  Mutually exclusive with `anchor`.  **Changes**: Deprecated in Zulip 3.0, replaced by `anchor=\"first_unread\"` instead. 
#'
#' #Get messages
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$GetMessages(var.num.before, var.num.after, anchor=var.anchor, narrow=var.narrow, client.gravatar=var.client.gravatar, apply.markdown=var.apply.markdown, use.first.unread.anchor=var.use.first.unread.anchor)
#'
#'
#' ####################  GetRawMessage  ####################
#'
#' library(openapi)
#' var.message.id <- 42 # integer | The target message's ID. 
#'
#' #Get a message's raw Markdown
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$GetRawMessage(var.message.id)
#'
#'
#' ####################  MarkAllAsRead  ####################
#'
#' library(openapi)
#'
#' #Mark all messages as read
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$MarkAllAsRead()
#'
#'
#' ####################  MarkStreamAsRead  ####################
#'
#' library(openapi)
#' var.stream.id <- 42 # integer | The ID of the stream to access. 
#'
#' #Mark messages in a stream as read
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$MarkStreamAsRead(var.stream.id)
#'
#'
#' ####################  MarkTopicAsRead  ####################
#'
#' library(openapi)
#' var.stream.id <- 42 # integer | The ID of the stream to access. 
#' var.topic.name <- 'new coffee machine' # character | The name of the topic whose messages should be marked as read. 
#'
#' #Mark messages in a topic as read
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$MarkTopicAsRead(var.stream.id, var.topic.name)
#'
#'
#' ####################  RemoveReaction  ####################
#'
#' library(openapi)
#' var.message.id <- 42 # integer | The target message's ID. 
#' var.emoji.name <- 'octopus' # character | The target emoji's human-readable name.  To find an emoji's name, hover over a message to reveal three icons on the right, then click the smiley face icon. Images of available reaction emojis appear. Hover over the emoji you want, and note that emoji's text name. 
#' var.emoji.code <- '1f419' # character | A unique identifier, defining the specific emoji codepoint requested, within the namespace of the `reaction_type`.  For most API clients, you won't need this, but it's important for Zulip apps to handle rare corner cases when adding/removing votes on an emoji reaction added previously by another user.  If the existing reaction was added when the Zulip server was using a previous version of the emoji data mapping between Unicode codepoints and human-readable names, sending the `emoji_code` in the data for the original reaction allows the Zulip server to correctly interpret your upvote as an upvote rather than a reaction with a \"diffenent\" emoji. 
#' var.reaction.type <- 'unicode_emoji' # character | If an app is adding/removing a vote on an existing reaction, it should pass this parameter using the value the server provided for the existing reaction for specificity.  Supported values:  * `unicode_emoji`: Unicode emoji (`emoji_code` will be its Unicode codepoint). * `realm_emoji`: Custom emoji. (`emoji_code` will be its ID). * `zulip_extra_emoji`: Special emoji included with Zulip.  Exists to    namespace the `zulip` emoji.  **Changes**: In Zulip 3.0 (feature level 2), this become optional for [custom emoji](/help/add-custom-emoji); previously, this endpoint assumed `unicode_emoji` if this parameter was not specified. 
#'
#' #Remove an emoji reaction
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$RemoveReaction(var.message.id, emoji.name=var.emoji.name, emoji.code=var.emoji.code, reaction.type=var.reaction.type)
#'
#'
#' ####################  RenderMessage  ####################
#'
#' library(openapi)
#' var.content <- 'Hello' # character | The content of the message. Maximum message size of 10000 bytes. 
#'
#' #Render message
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$RenderMessage(var.content)
#'
#'
#' ####################  SendMessage  ####################
#'
#' library(openapi)
#' var.type <- 'private' # character | The type of message to be sent. `private` for a private message and `stream` for a stream message. 
#' var.to <- [56] # array[integer] | For stream messages, either the name or integer ID of the stream. For private messages, either a list containing integer user IDs or a list containing string email addresses.  **Changes**: Support for using user/stream IDs was added in Zulip 2.0.0. 
#' var.content <- 'Hello' # character | The content of the message. Maximum message size of 10000 bytes. 
#' var.topic <- 'Castle' # character | The topic of the message. Only required for stream messages (`type=\"stream\"`), ignored otherwise.  Maximum length of 60 characters.  **Changes**: New in Zulip 2.0.  Previous Zulip releases encoded this as `subject`, which is currently a deprecated alias. 
#' var.queue.id <- '1593114627:0' # character | For clients supporting [local echo](https://zulip.readthedocs.io/en/latest/subsystems/sending-messages.html#local-echo), the [event queue](/api/register-queue) ID for the client.  If passed, `local_id` is required.  If the message is successfully sent, the server will include `local_id` in the `message` event that the client with this `queue_id` will receive notifying it of the new message via [`GET /events`](/api/get-events).  This lets the client know unambiguously that it should replace the locally echoed message, rather than adding this new message (which would be correct if the user had sent the new message from another device). 
#' var.local.id <- '100.01' # character | For clients supporting local echo, a unique string-format identifier chosen freely by the client; the server will pass it back to the client without inspecting it, as described in the `queue_id` description. 
#'
#' #Send a message
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$SendMessage(var.type, var.to, var.content, topic=var.topic, queue.id=var.queue.id, local.id=var.local.id)
#'
#'
#' ####################  UpdateMessage  ####################
#'
#' library(openapi)
#' var.message.id <- 42 # integer | The target message's ID. 
#' var.topic <- 'Castle' # character | The topic to move the message(s) to, to request changing the topic. Should only be sent when changing the topic, and will throw an error if the target message is not a stream message.  Maximum length of 60 characters.  **Changes**: New in Zulip 2.0.  Previous Zulip releases encoded this as `subject`, which is currently a deprecated alias. 
#' var.propagate.mode <- 'change_one' # character | Which message(s) should be edited: just the one indicated in `message_id`, messages in the same topic that had been sent after this one, or all of them.  Only the default value of `change_one` is valid when editing only the content of a message.  This parameter determines both which messages get moved and also whether clients that are currently narrowed to the topic containing the message should navigate or adjust their compose box recipient to point to the post-edit stream/topic. 
#' var.send.notification.to.old.thread <- TRUE # character | Whether to send breadcrumb message to the old thread to notify users where the messages were moved to.  **Changes**: New in Zulip 3.0 (feature level 9). 
#' var.send.notification.to.new.thread <- TRUE # character | Whether to send a notification message to the new thread to notify users where the messages came from.  **Changes**: New in Zulip 3.0 (feature level 9). 
#' var.content <- 'Hello' # character | The content of the message. Maximum message size of 10000 bytes. 
#' var.stream.id <- 42 # integer | The stream ID to move the message(s) to, to request moving messages to another stream.  Should only be sent when changing the stream, and will throw an error if the target message is not a stream message. 
#'
#' #Edit a message
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$UpdateMessage(var.message.id, topic=var.topic, propagate.mode=var.propagate.mode, send.notification.to.old.thread=var.send.notification.to.old.thread, send.notification.to.new.thread=var.send.notification.to.new.thread, content=var.content, stream.id=var.stream.id)
#'
#'
#' ####################  UpdateMessageFlags  ####################
#'
#' library(openapi)
#' var.messages <- [56] # array[integer] | An array containing the IDs of the target messages. 
#' var.op <- 'add' # character | Whether to `add` the flag or `remove` it. 
#' var.flag <- 'read' # character | The flag that should be added/removed. 
#'
#' #Update personal message flags
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$UpdateMessageFlags(var.messages, var.op, var.flag)
#'
#'
#' ####################  UploadFile  ####################
#'
#' library(openapi)
#' var.filename <- File.new('/path/to/file') # data.frame | 
#'
#' #Upload a file
#' api.instance <- MessagesApi$new()
#'
#' result <- api.instance$UploadFile(filename=var.filename)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
MessagesApi <- R6::R6Class(
  'MessagesApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    AddReaction = function(message.id, emoji.name, emoji.code=NULL, reaction.type=NULL, ...){
      apiResponse <- self$AddReactionWithHttpInfo(message.id, emoji.name, emoji.code, reaction.type, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    AddReactionWithHttpInfo = function(message.id, emoji.name, emoji.code=NULL, reaction.type=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`message.id`)) {
        stop("Missing required parameter `message.id`.")
      }

      if (missing(`emoji.name`)) {
        stop("Missing required parameter `emoji.name`.")
      }

      queryParams['emoji_name'] <- emoji.name

      queryParams['emoji_code'] <- emoji.code

      queryParams['reaction_type'] <- reaction.type

      body <- NULL
      urlPath <- "/messages/{message_id}/reactions"
      if (!missing(`message.id`)) {
        urlPath <- gsub(paste0("\\{", "message_id", "\\}"), URLencode(as.character(`message.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    CheckMessagesMatchNarrow = function(msg.ids, narrow, ...){
      apiResponse <- self$CheckMessagesMatchNarrowWithHttpInfo(msg.ids, narrow, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CheckMessagesMatchNarrowWithHttpInfo = function(msg.ids, narrow, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`msg.ids`)) {
        stop("Missing required parameter `msg.ids`.")
      }

      if (missing(`narrow`)) {
        stop("Missing required parameter `narrow`.")
      }

      queryParams['msg_ids'] <- msg.ids

      queryParams['narrow'] <- narrow

      body <- NULL
      urlPath <- "/messages/matches_narrow"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteMessage = function(message.id, ...){
      apiResponse <- self$DeleteMessageWithHttpInfo(message.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteMessageWithHttpInfo = function(message.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`message.id`)) {
        stop("Missing required parameter `message.id`.")
      }

      body <- NULL
      urlPath <- "/messages/{message_id}"
      if (!missing(`message.id`)) {
        urlPath <- gsub(paste0("\\{", "message_id", "\\}"), URLencode(as.character(`message.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetFileTemporaryUrl = function(realm.id.str, filename, ...){
      apiResponse <- self$GetFileTemporaryUrlWithHttpInfo(realm.id.str, filename, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetFileTemporaryUrlWithHttpInfo = function(realm.id.str, filename, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`realm.id.str`)) {
        stop("Missing required parameter `realm.id.str`.")
      }

      if (missing(`filename`)) {
        stop("Missing required parameter `filename`.")
      }

      body <- NULL
      urlPath <- "/user_uploads/{realm_id_str}/{filename}"
      if (!missing(`realm.id.str`)) {
        urlPath <- gsub(paste0("\\{", "realm_id_str", "\\}"), URLencode(as.character(`realm.id.str`), reserved = TRUE), urlPath)
      }

      if (!missing(`filename`)) {
        urlPath <- gsub(paste0("\\{", "filename", "\\}"), URLencode(as.character(`filename`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetMessageHistory = function(message.id, ...){
      apiResponse <- self$GetMessageHistoryWithHttpInfo(message.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetMessageHistoryWithHttpInfo = function(message.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`message.id`)) {
        stop("Missing required parameter `message.id`.")
      }

      body <- NULL
      urlPath <- "/messages/{message_id}/history"
      if (!missing(`message.id`)) {
        urlPath <- gsub(paste0("\\{", "message_id", "\\}"), URLencode(as.character(`message.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetMessages = function(num.before, num.after, anchor=NULL, narrow=[], client.gravatar=FALSE, apply.markdown=TRUE, use.first.unread.anchor=FALSE, ...){
      apiResponse <- self$GetMessagesWithHttpInfo(num.before, num.after, anchor, narrow, client.gravatar, apply.markdown, use.first.unread.anchor, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetMessagesWithHttpInfo = function(num.before, num.after, anchor=NULL, narrow=[], client.gravatar=FALSE, apply.markdown=TRUE, use.first.unread.anchor=FALSE, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`num.before`)) {
        stop("Missing required parameter `num.before`.")
      }

      if (missing(`num.after`)) {
        stop("Missing required parameter `num.after`.")
      }

      queryParams['anchor'] <- anchor

      queryParams['num_before'] <- num.before

      queryParams['num_after'] <- num.after

      queryParams['narrow'] <- narrow

      queryParams['client_gravatar'] <- client.gravatar

      queryParams['apply_markdown'] <- apply.markdown

      queryParams['use_first_unread_anchor'] <- use.first.unread.anchor

      body <- NULL
      urlPath <- "/messages"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetRawMessage = function(message.id, ...){
      apiResponse <- self$GetRawMessageWithHttpInfo(message.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetRawMessageWithHttpInfo = function(message.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`message.id`)) {
        stop("Missing required parameter `message.id`.")
      }

      body <- NULL
      urlPath <- "/messages/{message_id}"
      if (!missing(`message.id`)) {
        urlPath <- gsub(paste0("\\{", "message_id", "\\}"), URLencode(as.character(`message.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    MarkAllAsRead = function(...){
      apiResponse <- self$MarkAllAsReadWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    MarkAllAsReadWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/mark_all_as_read"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    MarkStreamAsRead = function(stream.id, ...){
      apiResponse <- self$MarkStreamAsReadWithHttpInfo(stream.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    MarkStreamAsReadWithHttpInfo = function(stream.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`stream.id`)) {
        stop("Missing required parameter `stream.id`.")
      }

      queryParams['stream_id'] <- stream.id

      body <- NULL
      urlPath <- "/mark_stream_as_read"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    MarkTopicAsRead = function(stream.id, topic.name, ...){
      apiResponse <- self$MarkTopicAsReadWithHttpInfo(stream.id, topic.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    MarkTopicAsReadWithHttpInfo = function(stream.id, topic.name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`stream.id`)) {
        stop("Missing required parameter `stream.id`.")
      }

      if (missing(`topic.name`)) {
        stop("Missing required parameter `topic.name`.")
      }

      queryParams['stream_id'] <- stream.id

      queryParams['topic_name'] <- topic.name

      body <- NULL
      urlPath <- "/mark_topic_as_read"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RemoveReaction = function(message.id, emoji.name=NULL, emoji.code=NULL, reaction.type=NULL, ...){
      apiResponse <- self$RemoveReactionWithHttpInfo(message.id, emoji.name, emoji.code, reaction.type, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RemoveReactionWithHttpInfo = function(message.id, emoji.name=NULL, emoji.code=NULL, reaction.type=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`message.id`)) {
        stop("Missing required parameter `message.id`.")
      }

      queryParams['emoji_name'] <- emoji.name

      queryParams['emoji_code'] <- emoji.code

      queryParams['reaction_type'] <- reaction.type

      body <- NULL
      urlPath <- "/messages/{message_id}/reactions"
      if (!missing(`message.id`)) {
        urlPath <- gsub(paste0("\\{", "message_id", "\\}"), URLencode(as.character(`message.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RenderMessage = function(content, ...){
      apiResponse <- self$RenderMessageWithHttpInfo(content, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RenderMessageWithHttpInfo = function(content, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`content`)) {
        stop("Missing required parameter `content`.")
      }

      queryParams['content'] <- content

      body <- NULL
      urlPath <- "/messages/render"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    SendMessage = function(type, to, content, topic=NULL, queue.id=NULL, local.id=NULL, ...){
      apiResponse <- self$SendMessageWithHttpInfo(type, to, content, topic, queue.id, local.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    SendMessageWithHttpInfo = function(type, to, content, topic=NULL, queue.id=NULL, local.id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`type`)) {
        stop("Missing required parameter `type`.")
      }

      if (missing(`to`)) {
        stop("Missing required parameter `to`.")
      }

      if (missing(`content`)) {
        stop("Missing required parameter `content`.")
      }

      queryParams['type'] <- type

      queryParams['to'] <- to

      queryParams['content'] <- content

      queryParams['topic'] <- topic

      queryParams['queue_id'] <- queue.id

      queryParams['local_id'] <- local.id

      body <- NULL
      urlPath <- "/messages"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UpdateMessage = function(message.id, topic=NULL, propagate.mode='change_one', send.notification.to.old.thread=TRUE, send.notification.to.new.thread=TRUE, content=NULL, stream.id=NULL, ...){
      apiResponse <- self$UpdateMessageWithHttpInfo(message.id, topic, propagate.mode, send.notification.to.old.thread, send.notification.to.new.thread, content, stream.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UpdateMessageWithHttpInfo = function(message.id, topic=NULL, propagate.mode='change_one', send.notification.to.old.thread=TRUE, send.notification.to.new.thread=TRUE, content=NULL, stream.id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`message.id`)) {
        stop("Missing required parameter `message.id`.")
      }

      queryParams['topic'] <- topic

      queryParams['propagate_mode'] <- propagate.mode

      queryParams['send_notification_to_old_thread'] <- send.notification.to.old.thread

      queryParams['send_notification_to_new_thread'] <- send.notification.to.new.thread

      queryParams['content'] <- content

      queryParams['stream_id'] <- stream.id

      body <- NULL
      urlPath <- "/messages/{message_id}"
      if (!missing(`message.id`)) {
        urlPath <- gsub(paste0("\\{", "message_id", "\\}"), URLencode(as.character(`message.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PATCH",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccess", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UpdateMessageFlags = function(messages, op, flag, ...){
      apiResponse <- self$UpdateMessageFlagsWithHttpInfo(messages, op, flag, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UpdateMessageFlagsWithHttpInfo = function(messages, op, flag, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`messages`)) {
        stop("Missing required parameter `messages`.")
      }

      if (missing(`op`)) {
        stop("Missing required parameter `op`.")
      }

      if (missing(`flag`)) {
        stop("Missing required parameter `flag`.")
      }

      queryParams['messages'] <- messages

      queryParams['op'] <- op

      queryParams['flag'] <- flag

      body <- NULL
      urlPath <- "/messages/flags"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UploadFile = function(filename=NULL, ...){
      apiResponse <- self$UploadFileWithHttpInfo(filename, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UploadFileWithHttpInfo = function(filename=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- list(
        "filename" = httr::upload_file(filename)
      )

      urlPath <- "/user_uploads"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JsonSuccessBase", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
