/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIApiKeyResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIApiKeyResponse::OAIApiKeyResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIApiKeyResponse::OAIApiKeyResponse() {
    this->initializeModel();
}

OAIApiKeyResponse::~OAIApiKeyResponse() {}

void OAIApiKeyResponse::initializeModel() {

    m_result_isSet = false;
    m_result_isValid = false;

    m_msg_isSet = false;
    m_msg_isValid = false;

    m_api_key_isSet = false;
    m_api_key_isValid = false;

    m_email_isSet = false;
    m_email_isValid = false;
}

void OAIApiKeyResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIApiKeyResponse::fromJsonObject(QJsonObject json) {

    m_result_isValid = ::OpenAPI::fromJsonValue(result, json[QString("result")]);
    m_result_isSet = !json[QString("result")].isNull() && m_result_isValid;

    m_msg_isValid = ::OpenAPI::fromJsonValue(msg, json[QString("msg")]);
    m_msg_isSet = !json[QString("msg")].isNull() && m_msg_isValid;

    m_api_key_isValid = ::OpenAPI::fromJsonValue(api_key, json[QString("api_key")]);
    m_api_key_isSet = !json[QString("api_key")].isNull() && m_api_key_isValid;

    m_email_isValid = ::OpenAPI::fromJsonValue(email, json[QString("email")]);
    m_email_isSet = !json[QString("email")].isNull() && m_email_isValid;
}

QString OAIApiKeyResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIApiKeyResponse::asJsonObject() const {
    QJsonObject obj;
    if (m_result_isSet) {
        obj.insert(QString("result"), ::OpenAPI::toJsonValue(result));
    }
    if (m_msg_isSet) {
        obj.insert(QString("msg"), ::OpenAPI::toJsonValue(msg));
    }
    if (m_api_key_isSet) {
        obj.insert(QString("api_key"), ::OpenAPI::toJsonValue(api_key));
    }
    if (m_email_isSet) {
        obj.insert(QString("email"), ::OpenAPI::toJsonValue(email));
    }
    return obj;
}

OAIAnyType OAIApiKeyResponse::getResult() const {
    return result;
}
void OAIApiKeyResponse::setResult(const OAIAnyType &result) {
    this->result = result;
    this->m_result_isSet = true;
}

bool OAIApiKeyResponse::is_result_Set() const{
    return m_result_isSet;
}

bool OAIApiKeyResponse::is_result_Valid() const{
    return m_result_isValid;
}

OAIAnyType OAIApiKeyResponse::getMsg() const {
    return msg;
}
void OAIApiKeyResponse::setMsg(const OAIAnyType &msg) {
    this->msg = msg;
    this->m_msg_isSet = true;
}

bool OAIApiKeyResponse::is_msg_Set() const{
    return m_msg_isSet;
}

bool OAIApiKeyResponse::is_msg_Valid() const{
    return m_msg_isValid;
}

QString OAIApiKeyResponse::getApiKey() const {
    return api_key;
}
void OAIApiKeyResponse::setApiKey(const QString &api_key) {
    this->api_key = api_key;
    this->m_api_key_isSet = true;
}

bool OAIApiKeyResponse::is_api_key_Set() const{
    return m_api_key_isSet;
}

bool OAIApiKeyResponse::is_api_key_Valid() const{
    return m_api_key_isValid;
}

QString OAIApiKeyResponse::getEmail() const {
    return email;
}
void OAIApiKeyResponse::setEmail(const QString &email) {
    this->email = email;
    this->m_email_isSet = true;
}

bool OAIApiKeyResponse::is_email_Set() const{
    return m_email_isSet;
}

bool OAIApiKeyResponse::is_email_Valid() const{
    return m_email_isValid;
}

bool OAIApiKeyResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_result_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_msg_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_api_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_email_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIApiKeyResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_result_isValid && m_msg_isValid && m_api_key_isValid && m_email_isValid && true;
}

} // namespace OpenAPI
