/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIEmojiBase.h
 *
 * 
 */

#ifndef OAIEmojiBase_H
#define OAIEmojiBase_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIEmojiBase : public OAIObject {
public:
    OAIEmojiBase();
    OAIEmojiBase(QString json);
    ~OAIEmojiBase() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getEmojiCode() const;
    void setEmojiCode(const QString &emoji_code);
    bool is_emoji_code_Set() const;
    bool is_emoji_code_Valid() const;

    QString getEmojiName() const;
    void setEmojiName(const QString &emoji_name);
    bool is_emoji_name_Set() const;
    bool is_emoji_name_Valid() const;

    QString getReactionType() const;
    void setReactionType(const QString &reaction_type);
    bool is_reaction_type_Set() const;
    bool is_reaction_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString emoji_code;
    bool m_emoji_code_isSet;
    bool m_emoji_code_isValid;

    QString emoji_name;
    bool m_emoji_name_isSet;
    bool m_emoji_name_isValid;

    QString reaction_type;
    bool m_reaction_type_isSet;
    bool m_reaction_type_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIEmojiBase)

#endif // OAIEmojiBase_H
