# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ZulipRESTAPI.Model.AttachmentsMessages do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"date_sent",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"date_sent" => integer() | nil,
    :"id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: ZulipRESTAPI.Model.AttachmentsMessages do
  def decode(value, _options) do
    value
  end
end

