#
# Zulip REST API
# Powerful open source group chat 
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DraftsApi' {
    Context 'New-Drafts' {
        It 'Test New-Drafts' {
            #$TestResult = New-Drafts -Drafts "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteDraft' {
        It 'Test Invoke-DeleteDraft' {
            #$TestResult = Invoke-DeleteDraft -DraftId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Edit-Draft' {
        It 'Test Edit-Draft' {
            #$TestResult = Edit-Draft -DraftId "TEST_VALUE" -Draft "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-Drafts' {
        It 'Test Get-Drafts' {
            #$TestResult = Get-Drafts
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
