<?php
/**
 * RealmEmojiTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Zulip REST API
 *
 * Powerful open source group chat
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * RealmEmojiTest Class Doc Comment
 *
 * @category    Class */
// * @description &#x60;{emoji_id}&#x60;: Object containing details about the emoji with  the specified ID. It has the following properties:
/**
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class RealmEmojiTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RealmEmoji"
     */
    public function testRealmEmoji()
    {
        $testRealmEmoji = new RealmEmoji();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "sourceUrl"
     */
    public function testPropertySourceUrl()
    {
    }

    /**
     * Test attribute "deactivated"
     */
    public function testPropertyDeactivated()
    {
    }

    /**
     * Test attribute "authorId"
     */
    public function testPropertyAuthorId()
    {
    }
}
