# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.basic_stream_all_of import BasicStreamAllOf
from openapi_server.models.basic_stream_base import BasicStreamBase


class BasicStream(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BasicStream - a model defined in OpenAPI

        stream_id: The stream_id of this BasicStream [Optional].
        name: The name of this BasicStream [Optional].
        description: The description of this BasicStream [Optional].
        date_created: The date_created of this BasicStream [Optional].
        invite_only: The invite_only of this BasicStream [Optional].
        rendered_description: The rendered_description of this BasicStream [Optional].
        is_web_public: The is_web_public of this BasicStream [Optional].
        stream_post_policy: The stream_post_policy of this BasicStream [Optional].
        message_retention_days: The message_retention_days of this BasicStream [Optional].
        history_public_to_subscribers: The history_public_to_subscribers of this BasicStream [Optional].
        first_message_id: The first_message_id of this BasicStream [Optional].
        is_announcement_only: The is_announcement_only of this BasicStream [Optional].
    """

    stream_id: Optional[object] = None
    name: Optional[object] = None
    description: Optional[object] = None
    date_created: Optional[object] = None
    invite_only: Optional[object] = None
    rendered_description: Optional[object] = None
    is_web_public: Optional[object] = None
    stream_post_policy: Optional[object] = None
    message_retention_days: Optional[object] = None
    history_public_to_subscribers: Optional[object] = None
    first_message_id: Optional[object] = None
    is_announcement_only: Optional[object] = None

BasicStream.update_forward_refs()
