# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.get_messages_all_of import GetMessagesAllOf
from openapi_server.models.messages_base import MessagesBase


class GetMessages(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetMessages - a model defined in OpenAPI

        avatar_url: The avatar_url of this GetMessages [Optional].
        client: The client of this GetMessages [Optional].
        content: The content of this GetMessages [Optional].
        content_type: The content_type of this GetMessages [Optional].
        display_recipient: The display_recipient of this GetMessages [Optional].
        id: The id of this GetMessages [Optional].
        is_me_message: The is_me_message of this GetMessages [Optional].
        reactions: The reactions of this GetMessages [Optional].
        recipient_id: The recipient_id of this GetMessages [Optional].
        sender_email: The sender_email of this GetMessages [Optional].
        sender_full_name: The sender_full_name of this GetMessages [Optional].
        sender_id: The sender_id of this GetMessages [Optional].
        sender_realm_str: The sender_realm_str of this GetMessages [Optional].
        stream_id: The stream_id of this GetMessages [Optional].
        subject: The subject of this GetMessages [Optional].
        topic_links: The topic_links of this GetMessages [Optional].
        submessages: The submessages of this GetMessages [Optional].
        timestamp: The timestamp of this GetMessages [Optional].
        type: The type of this GetMessages [Optional].
        flags: The flags of this GetMessages [Optional].
        last_edit_timestamp: The last_edit_timestamp of this GetMessages [Optional].
        match_content: The match_content of this GetMessages [Optional].
        match_subject: The match_subject of this GetMessages [Optional].
    """

    avatar_url: Optional[object] = None
    client: Optional[object] = None
    content: Optional[object] = None
    content_type: Optional[object] = None
    display_recipient: Optional[object] = None
    id: Optional[object] = None
    is_me_message: Optional[object] = None
    reactions: Optional[object] = None
    recipient_id: Optional[object] = None
    sender_email: Optional[object] = None
    sender_full_name: Optional[object] = None
    sender_id: Optional[object] = None
    sender_realm_str: Optional[object] = None
    stream_id: Optional[object] = None
    subject: Optional[object] = None
    topic_links: Optional[object] = None
    submessages: Optional[object] = None
    timestamp: Optional[object] = None
    type: Optional[object] = None
    flags: Optional[List[str]] = None
    last_edit_timestamp: Optional[int] = None
    match_content: Optional[str] = None
    match_subject: Optional[str] = None

GetMessages.update_forward_refs()
