/*
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.CodedError;
import com.prokarma.pkmst.model.Draft;
import com.prokarma.pkmst.model.JsonError;
import com.prokarma.pkmst.model.JsonSuccess;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for DraftsApi
 */
@Ignore
public class DraftsApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final DraftsApi api = new DraftsApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Create drafts
     *
     * Create one or more drafts on the server. These drafts will be automatically synchronized to other clients via &#x60;drafts&#x60; events.  &#x60;POST {{ api_url }}/v1/drafts&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createDraftsTest() throws Exception {
        List<Draft> drafts = null;
    ResponseEntity<JsonSuccess> response = api.createDrafts(drafts , accept);

        // TODO: test validations
    }
    
    /**
     * Delete a draft
     *
     * Delete a single draft from the server. The deletion will be automatically synchronized to other clients via a &#x60;drafts&#x60; event.  &#x60;DELETE {{ api_url }}/v1/drafts/{draft_id}&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteDraftTest() throws Exception {
        Integer draftId = null;
    ResponseEntity<JsonSuccess> response = api.deleteDraft(draftId , accept);

        // TODO: test validations
    }
    
    /**
     * Edit a draft
     *
     * Edit a draft on the server. The edit will be automatically synchronized to other clients via &#x60;drafts&#x60; events.  &#x60;PATCH {{ api_url }}/v1/drafts/{draft_id}&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void editDraftTest() throws Exception {
        Integer draftId = null;
        Draft draft = null;
    ResponseEntity<JsonSuccess> response = api.editDraft(draftId, draft , accept);

        // TODO: test validations
    }
    
    /**
     * Get drafts
     *
     * Fetch all drafts for the current user.  &#x60;GET {{ api_url }}/v1/drafts&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDraftsTest() throws Exception {
    ResponseEntity<JsonSuccess> response = api.getDrafts(  accept);

        // TODO: test validations
    }
    
}
