/*
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.CodedError;
import java.io.File;
import com.prokarma.pkmst.model.InvalidMessageError;
import com.prokarma.pkmst.model.JsonSuccess;
import com.prokarma.pkmst.model.JsonSuccessBase;
import com.prokarma.pkmst.model.OneOfobjectobject;
import com.prokarma.pkmst.model.OneOfstringinteger;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for MessagesApi
 */
@Ignore
public class MessagesApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final MessagesApi api = new MessagesApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Add an emoji reaction
     *
     * Add an [emoji reaction](/help/emoji-reactions) to a message.  &#x60;POST {{ api_url }}/v1/messages/{message_id}/reactions&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addReactionTest() throws Exception {
        Integer messageId = null;
        String emojiName = null;
        String emojiCode = null;
        String reactionType = null;
    ResponseEntity<JsonSuccess> response = api.addReaction(messageId, emojiName, emojiCode, reactionType , accept);

        // TODO: test validations
    }
    
    /**
     * Check if messages match a narrow
     *
     * Check whether a set of messages match a [narrow](/api/construct-narrow).  &#x60;GET {{ api_url }}/v1/messages/matches_narrow&#x60;  For many common narrows (E.g. a topic), clients can write an efficient client-side check to determine whether a newly arrived message belongs in the view.  This endpoint is designed to allow clients to handle more complex narrows for which the client does not (or in the case of full-text search, cannot) implement this check.  The format of the &#x60;match_subject&#x60; and &#x60;match_content&#x60; objects is designed to match those of &#x60;GET /messages&#x60;, so that a client can splice these fields into a &#x60;message&#x60; object received from &#x60;GET /events&#x60; and end up with an extended message object identical to how a &#x60;GET /messages&#x60; for the current narrow would have returned the message. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void checkMessagesMatchNarrowTest() throws Exception {
        List<Integer> msgIds = null;
        List<Object> narrow = null;
    ResponseEntity<Object> response = api.checkMessagesMatchNarrow(msgIds, narrow , accept);

        // TODO: test validations
    }
    
    /**
     * Delete a message
     *
     * Permanently delete a message.  &#x60;DELETE {{ api_url }}/v1/messages/{msg_id}&#x60;  This API corresponds to the [delete a message completely][delete-completely] feature documented in the Zulip Help Center.  [delete-completely]: /help/edit-or-delete-a-message#delete-a-message-completely 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteMessageTest() throws Exception {
        Integer messageId = null;
    ResponseEntity<JsonSuccess> response = api.deleteMessage(messageId , accept);

        // TODO: test validations
    }
    
    /**
     * Get public temporary URL
     *
     * Get a temporary URL for access to the file that doesn&#39;t require authentication. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFileTemporaryUrlTest() throws Exception {
        Integer realmIdStr = null;
        String filename = null;
    ResponseEntity<JsonSuccessBase> response = api.getFileTemporaryUrl(realmIdStr, filename , accept);

        // TODO: test validations
    }
    
    /**
     * Get a message&#39;s edit history
     *
     * Fetch the message edit history of a previously edited message.  &#x60;GET {{ api_url }}/v1/messages/{message_id}/history&#x60;  Note that edit history may be disabled in some organizations; see the [Zulip Help Center documentation on editing messages][edit-settings].  [edit-settings]: /help/view-a-messages-edit-history 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMessageHistoryTest() throws Exception {
        Integer messageId = null;
    ResponseEntity<JsonSuccessBase> response = api.getMessageHistory(messageId , accept);

        // TODO: test validations
    }
    
    /**
     * Get messages
     *
     * Fetch message history from a Zulip server.  &#x60;GET {{ api_url }}/v1/messages&#x60;  This &#x60;GET /api/v1/messages&#x60; endpoint is the primary way to fetch message history from a Zulip server.  It is useful both for Zulip clients (e.g. the web, desktop, mobile, and terminal clients) as well as bots, API clients, backup scripts, etc.  By specifying a [narrow filter](/api/construct-narrow), you can use this endpoint to fetch the messages matching any search query that is supported by Zulip&#39;s powerful full-text search backend.  When a narrow is not specified, it can be used to fetch a user&#39;s message history. (We recommend paginating to 1000 messages at a time.)  In either case, you specify an &#x60;anchor&#x60; message (or ask the server to calculate the first unread message for you and use that as the anchor), as well as a number of messages before and after the anchor message.  The server returns those messages, sorted by message ID, as well as some metadata that makes it easy for a client to determine whether there are more messages matching the query that were not returned due to the &#x60;num_before&#x60; and &#x60;num_after&#x60; limits.  We recommend using &#x60;num_before &lt;&#x3D; 1000&#x60; and &#x60;num_after &lt;&#x3D; 1000&#x60; to avoid generating very large HTTP responses. A maximum of 5000 messages can be obtained per request; attempting to exceed this will result in an error. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMessagesTest() throws Exception {
        Integer numBefore = null;
        Integer numAfter = null;
        OneOfstringinteger anchor = null;
        List<Object> narrow = null;
        Boolean clientGravatar = null;
        Boolean applyMarkdown = null;
        Boolean useFirstUnreadAnchor = null;
    ResponseEntity<JsonSuccessBase> response = api.getMessages(numBefore, numAfter, anchor, narrow, clientGravatar, applyMarkdown, useFirstUnreadAnchor , accept);

        // TODO: test validations
    }
    
    /**
     * Get a message&#39;s raw Markdown
     *
     * Get the raw content of a message.  &#x60;GET {{ api_url }}/v1/messages/{msg_id}&#x60;  This is a rarely-used endpoint relevant for clients that primarily work with HTML-rendered messages but might need to occasionally fetch the message&#39;s raw Markdown (e.g. for pre-filling a message-editing UI). 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRawMessageTest() throws Exception {
        Integer messageId = null;
    ResponseEntity<JsonSuccessBase> response = api.getRawMessage(messageId , accept);

        // TODO: test validations
    }
    
    /**
     * Mark all messages as read
     *
     * Marks all of the current user&#39;s unread messages as read.  &#x60;POST {{ api_url }}/v1/mark_all_as_read&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void markAllAsReadTest() throws Exception {
    ResponseEntity<JsonSuccess> response = api.markAllAsRead(  accept);

        // TODO: test validations
    }
    
    /**
     * Mark messages in a stream as read
     *
     * Mark all the unread messages in a stream as read. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void markStreamAsReadTest() throws Exception {
        Integer streamId = null;
    ResponseEntity<JsonSuccess> response = api.markStreamAsRead(streamId , accept);

        // TODO: test validations
    }
    
    /**
     * Mark messages in a topic as read
     *
     * Mark all the unread messages in a topic as read. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void markTopicAsReadTest() throws Exception {
        Integer streamId = null;
        String topicName = null;
    ResponseEntity<JsonSuccess> response = api.markTopicAsRead(streamId, topicName , accept);

        // TODO: test validations
    }
    
    /**
     * Remove an emoji reaction
     *
     * Remove an [emoji reaction](/help/emoji-reactions) from a message.  &#x60;DELETE {{ api_url }}/v1/messages/{message_id}/reactions&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void removeReactionTest() throws Exception {
        Integer messageId = null;
        String emojiName = null;
        String emojiCode = null;
        String reactionType = null;
    ResponseEntity<JsonSuccess> response = api.removeReaction(messageId, emojiName, emojiCode, reactionType , accept);

        // TODO: test validations
    }
    
    /**
     * Render message
     *
     * Render a message to HTML.  &#x60;POST {{ api_url }}/v1/messages/render&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void renderMessageTest() throws Exception {
        String content = null;
    ResponseEntity<JsonSuccessBase> response = api.renderMessage(content , accept);

        // TODO: test validations
    }
    
    /**
     * Send a message
     *
     * Send a stream or a private message.  &#x60;POST {{ api_url }}/v1/messages&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendMessageTest() throws Exception {
        String type = null;
        List<Integer> to = null;
        String content = null;
        String topic = null;
        String queueId = null;
        String localId = null;
    ResponseEntity<JsonSuccessBase> response = api.sendMessage(type, to, content, topic, queueId, localId , accept);

        // TODO: test validations
    }
    
    /**
     * Edit a message
     *
     * Edit/update the content or topic of a message.  &#x60;PATCH {{ api_url }}/v1/messages/{msg_id}&#x60;  &#x60;{msg_id}&#x60; in the above URL should be replaced with the ID of the message you wish you update.  You can [resolve topics](/help/resolve-a-topic) by editing the topic to &#x60;✔ {original_topic}&#x60;.  **Note**: See [configuring message editing][config-message-editing] for detailed documentation on when users are allowed to edit topics.  [config-message-editing]: /help/configure-message-editing-and-deletion 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateMessageTest() throws Exception {
        Integer messageId = null;
        String topic = null;
        String propagateMode = null;
        Boolean sendNotificationToOldThread = null;
        Boolean sendNotificationToNewThread = null;
        String content = null;
        Integer streamId = null;
    ResponseEntity<JsonSuccess> response = api.updateMessage(messageId, topic, propagateMode, sendNotificationToOldThread, sendNotificationToNewThread, content, streamId , accept);

        // TODO: test validations
    }
    
    /**
     * Update personal message flags
     *
     * Add or remove personal message flags like &#x60;read&#x60; and &#x60;starred&#x60; on a collection of message IDs.  &#x60;POST {{ api_url }}/v1/messages/flags&#x60;  For updating the &#x60;read&#x60; flag on common collections of messages, see also the [special endpoints for marking message as read in bulk](/api/mark-all-as-read). 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateMessageFlagsTest() throws Exception {
        List<Integer> messages = null;
        String op = null;
        String flag = null;
    ResponseEntity<JsonSuccessBase> response = api.updateMessageFlags(messages, op, flag , accept);

        // TODO: test validations
    }
    
    /**
     * Upload a file
     *
     * Upload a single file and get the corresponding URI.  &#x60;POST {{ api_url }}/v1/user_uploads&#x60;  Initially, only you will be able to access the link.  To share the uploaded file, you&#39;ll need to [send a message][send-message] containing the resulting link.  Users who can already access the link can reshare it with other users by sending additional Zulip messages containing the link.  [uploaded-files]: /help/manage-your-uploaded-files [send-message]: /api/send-message 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadFileTest() throws Exception {
        MultipartFile filename = null;
    ResponseEntity<JsonSuccessBase> response = api.uploadFile(filename , accept);

        // TODO: test validations
    }
    
}
