/*
 * Zulip REST API
 *
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EmojiReactionBaseUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmojiReactionBaseUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmojiReactionBaseUser
        //private EmojiReactionBaseUser instance;

        public EmojiReactionBaseUserTests()
        {
            // TODO uncomment below to create an instance of EmojiReactionBaseUser
            //instance = new EmojiReactionBaseUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmojiReactionBaseUser
        /// </summary>
        [Fact]
        public void EmojiReactionBaseUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmojiReactionBaseUser
            //Assert.IsType<EmojiReactionBaseUser>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'IsMirrorDummy'
        /// </summary>
        [Fact]
        public void IsMirrorDummyTest()
        {
            // TODO unit test for the property 'IsMirrorDummy'
        }

    }

}
