/**
* Zulip REST API
* Powerful open source group chat 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.api.model

import org.openapitools.server.api.model.AnyType
import org.openapitools.server.api.model.BasicStreamAllOf
import org.openapitools.server.api.model.BasicStreamBase

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param streamId 
 * @param name 
 * @param description 
 * @param dateCreated 
 * @param inviteOnly 
 * @param renderedDescription 
 * @param isWebPublic 
 * @param streamPostPolicy 
 * @param messageRetentionDays 
 * @param historyPublicToSubscribers 
 * @param firstMessageId 
 * @param isAnnouncementOnly 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class BasicStream (
    val streamId: AnyType? = null,
    val name: AnyType? = null,
    val description: AnyType? = null,
    val dateCreated: AnyType? = null,
    val inviteOnly: AnyType? = null,
    val renderedDescription: AnyType? = null,
    val isWebPublic: AnyType? = null,
    val streamPostPolicy: AnyType? = null,
    val messageRetentionDays: AnyType? = null,
    val historyPublicToSubscribers: AnyType? = null,
    val firstMessageId: AnyType? = null,
    val isAnnouncementOnly: AnyType? = null
) {

}

