--[[
  Zulip REST API
 
  Powerful open source group chat 
 
  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- api_key_response class
local api_key_response = {}
local api_key_response_mt = {
	__name = "api_key_response";
	__index = api_key_response;
}

local function cast_api_key_response(t)
	return setmetatable(t, api_key_response_mt)
end

local function new_api_key_response(result, msg, api_key, email)
	return cast_api_key_response({
		["result"] = result;
		["msg"] = msg;
		["api_key"] = api_key;
		["email"] = email;
	})
end

return {
	cast = cast_api_key_response;
	new = new_api_key_response;
}
