#
# Zulip REST API
# 
# Powerful open source group chat 
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_any_type
import model_api_key_response_all_of
import model_json_success_base

type ApiKeyResponse* = object
  ## 
  result*: AnyType
  msg*: AnyType
  apiKey*: string ## The API key that can be used to authenticate as the requested user. 
  email*: string ## The email address of the user who owns the API key 
