#
# Zulip REST API
# 
# Powerful open source group chat 
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_any_type
import model_coded_error_base
import model_missing_argument_error_all_of

type MissingArgumentError* = object
  ## 
  result*: AnyType
  msg*: AnyType
  code*: AnyType
  varName*: string ## It contains the information about the missing parameter. 
