# coding: utf-8

"""
    Zulip REST API

    Powerful open source group chat   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.messages_base import MessagesBase  # noqa: E501
from openapi_client.rest import ApiException

class TestMessagesBase(unittest.TestCase):
    """MessagesBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MessagesBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.messages_base.MessagesBase()  # noqa: E501
        if include_optional :
            return MessagesBase(
                avatar_url = '', 
                client = '', 
                content = '', 
                content_type = '', 
                display_recipient = None, 
                id = 56, 
                is_me_message = True, 
                reactions = [
                    null
                    ], 
                recipient_id = 56, 
                sender_email = '', 
                sender_full_name = '', 
                sender_id = 56, 
                sender_realm_str = '', 
                stream_id = 56, 
                subject = '', 
                topic_links = [
                    openapi_client.models.messages_base_topic_links.MessagesBase_topic_links(
                        text = '', 
                        url = '', )
                    ], 
                submessages = [
                    ''
                    ], 
                timestamp = 56, 
                type = ''
            )
        else :
            return MessagesBase(
        )

    def testMessagesBase(self):
        """Test MessagesBase"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
