/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnyType } from './AnyType';
import { HttpFile } from '../http/http';

export class CodedErrorBaseAllOf {
    'result'?: AnyType;
    'msg'?: AnyType;
    /**
    * A string that identifies the error. 
    */
    'code'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "AnyType",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "AnyType",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CodedErrorBaseAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

