// tslint:disable
/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvalidMessageErrorAllOf
 */
export interface InvalidMessageErrorAllOf  {
    /**
     * 
     * @type {any}
     * @memberof InvalidMessageErrorAllOf
     */
    result?: any;
    /**
     * 
     * @type {any}
     * @memberof InvalidMessageErrorAllOf
     */
    msg?: any;
    /**
     * The raw content of the message. 
     * @type {string}
     * @memberof InvalidMessageErrorAllOf
     */
    rawContent?: string;
}

export function InvalidMessageErrorAllOfFromJSON(json: any): InvalidMessageErrorAllOf {
    return {
        'result': !exists(json, 'result') ? undefined : json['result'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'rawContent': !exists(json, 'raw_content') ? undefined : json['raw_content'],
    };
}

export function InvalidMessageErrorAllOfToJSON(value?: InvalidMessageErrorAllOf): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'result': value.result,
        'msg': value.msg,
        'raw_content': value.rawContent,
    };
}


