#
# Zulip REST API
# Powerful open source group chat 
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'JsonErrorBase' {
    Context 'JsonErrorBase' {
        It 'Initialize-JsonErrorBase' {
            # a simple test to create an object
            #$NewObject = Initialize-JsonErrorBase -Result "TEST_VALUE" -Msg "TEST_VALUE"
            #$NewObject | Should -BeOfType JsonErrorBase
            #$NewObject.property | Should -Be 0
        }
    }
}
