#
# Zulip REST API
# Powerful open source group chat 
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'UserGroup' {
    Context 'UserGroup' {
        It 'Initialize-UserGroup' {
            # a simple test to create an object
            #$NewObject = Initialize-UserGroup -Name "TEST_VALUE" -Description "TEST_VALUE" -Members "TEST_VALUE" -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType UserGroup
            #$NewObject.property | Should -Be 0
        }
    }
}
