/**
* Zulip REST API
* Powerful open source group chat 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "BasicBotBase.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

BasicBotBase::BasicBotBase()
{
    m_User_id = 0;
    m_User_idIsSet = false;
    m_Full_name = "";
    m_Full_nameIsSet = false;
    m_Api_key = "";
    m_Api_keyIsSet = false;
    m_Default_sending_stream = "";
    m_Default_sending_streamIsSet = false;
    m_Default_events_register_stream = "";
    m_Default_events_register_streamIsSet = false;
    m_Default_all_public_streams = false;
    m_Default_all_public_streamsIsSet = false;
    m_Avatar_url = "";
    m_Avatar_urlIsSet = false;
    m_Owner_id = 0;
    m_Owner_idIsSet = false;
    m_ServicesIsSet = false;
    
}

void BasicBotBase::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool BasicBotBase::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool BasicBotBase::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "BasicBotBase" : pathPrefix;

                                         
    if (servicesIsSet())
    {
        const std::vector<OneOfobjectobject>& value = m_Services;
        const std::string currentValuePath = _pathPrefix + ".services";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const OneOfobjectobject& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".services") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool BasicBotBase::operator==(const BasicBotBase& rhs) const
{
    return
    
    
    
    ((!userIdIsSet() && !rhs.userIdIsSet()) || (userIdIsSet() && rhs.userIdIsSet() && getUserId() == rhs.getUserId())) &&
    
    
    ((!fullNameIsSet() && !rhs.fullNameIsSet()) || (fullNameIsSet() && rhs.fullNameIsSet() && getFullName() == rhs.getFullName())) &&
    
    
    ((!apiKeyIsSet() && !rhs.apiKeyIsSet()) || (apiKeyIsSet() && rhs.apiKeyIsSet() && getApiKey() == rhs.getApiKey())) &&
    
    
    ((!defaultSendingStreamIsSet() && !rhs.defaultSendingStreamIsSet()) || (defaultSendingStreamIsSet() && rhs.defaultSendingStreamIsSet() && getDefaultSendingStream() == rhs.getDefaultSendingStream())) &&
    
    
    ((!defaultEventsRegisterStreamIsSet() && !rhs.defaultEventsRegisterStreamIsSet()) || (defaultEventsRegisterStreamIsSet() && rhs.defaultEventsRegisterStreamIsSet() && getDefaultEventsRegisterStream() == rhs.getDefaultEventsRegisterStream())) &&
    
    
    ((!defaultAllPublicStreamsIsSet() && !rhs.defaultAllPublicStreamsIsSet()) || (defaultAllPublicStreamsIsSet() && rhs.defaultAllPublicStreamsIsSet() && isDefaultAllPublicStreams() == rhs.isDefaultAllPublicStreams())) &&
    
    
    ((!avatarUrlIsSet() && !rhs.avatarUrlIsSet()) || (avatarUrlIsSet() && rhs.avatarUrlIsSet() && getAvatarUrl() == rhs.getAvatarUrl())) &&
    
    
    ((!ownerIdIsSet() && !rhs.ownerIdIsSet()) || (ownerIdIsSet() && rhs.ownerIdIsSet() && getOwnerId() == rhs.getOwnerId())) &&
    
    
    ((!servicesIsSet() && !rhs.servicesIsSet()) || (servicesIsSet() && rhs.servicesIsSet() && getServices() == rhs.getServices()))
    
    ;
}

bool BasicBotBase::operator!=(const BasicBotBase& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const BasicBotBase& o)
{
    j = nlohmann::json();
    if(o.userIdIsSet())
        j["user_id"] = o.m_User_id;
    if(o.fullNameIsSet())
        j["full_name"] = o.m_Full_name;
    if(o.apiKeyIsSet())
        j["api_key"] = o.m_Api_key;
    if(o.defaultSendingStreamIsSet())
        j["default_sending_stream"] = o.m_Default_sending_stream;
    if(o.defaultEventsRegisterStreamIsSet())
        j["default_events_register_stream"] = o.m_Default_events_register_stream;
    if(o.defaultAllPublicStreamsIsSet())
        j["default_all_public_streams"] = o.m_Default_all_public_streams;
    if(o.avatarUrlIsSet())
        j["avatar_url"] = o.m_Avatar_url;
    if(o.ownerIdIsSet())
        j["owner_id"] = o.m_Owner_id;
    if(o.servicesIsSet() || !o.m_Services.empty())
        j["services"] = o.m_Services;
    
}

void from_json(const nlohmann::json& j, BasicBotBase& o)
{
    if(j.find("user_id") != j.end())
    {
        j.at("user_id").get_to(o.m_User_id);
        o.m_User_idIsSet = true;
    } 
    if(j.find("full_name") != j.end())
    {
        j.at("full_name").get_to(o.m_Full_name);
        o.m_Full_nameIsSet = true;
    } 
    if(j.find("api_key") != j.end())
    {
        j.at("api_key").get_to(o.m_Api_key);
        o.m_Api_keyIsSet = true;
    } 
    if(j.find("default_sending_stream") != j.end())
    {
        j.at("default_sending_stream").get_to(o.m_Default_sending_stream);
        o.m_Default_sending_streamIsSet = true;
    } 
    if(j.find("default_events_register_stream") != j.end())
    {
        j.at("default_events_register_stream").get_to(o.m_Default_events_register_stream);
        o.m_Default_events_register_streamIsSet = true;
    } 
    if(j.find("default_all_public_streams") != j.end())
    {
        j.at("default_all_public_streams").get_to(o.m_Default_all_public_streams);
        o.m_Default_all_public_streamsIsSet = true;
    } 
    if(j.find("avatar_url") != j.end())
    {
        j.at("avatar_url").get_to(o.m_Avatar_url);
        o.m_Avatar_urlIsSet = true;
    } 
    if(j.find("owner_id") != j.end())
    {
        j.at("owner_id").get_to(o.m_Owner_id);
        o.m_Owner_idIsSet = true;
    } 
    if(j.find("services") != j.end())
    {
        j.at("services").get_to(o.m_Services);
        o.m_ServicesIsSet = true;
    } 
    
}

int32_t BasicBotBase::getUserId() const
{
    return m_User_id;
}
void BasicBotBase::setUserId(int32_t const value)
{
    m_User_id = value;
    m_User_idIsSet = true;
}
bool BasicBotBase::userIdIsSet() const
{
    return m_User_idIsSet;
}
void BasicBotBase::unsetUser_id()
{
    m_User_idIsSet = false;
}
std::string BasicBotBase::getFullName() const
{
    return m_Full_name;
}
void BasicBotBase::setFullName(std::string const& value)
{
    m_Full_name = value;
    m_Full_nameIsSet = true;
}
bool BasicBotBase::fullNameIsSet() const
{
    return m_Full_nameIsSet;
}
void BasicBotBase::unsetFull_name()
{
    m_Full_nameIsSet = false;
}
std::string BasicBotBase::getApiKey() const
{
    return m_Api_key;
}
void BasicBotBase::setApiKey(std::string const& value)
{
    m_Api_key = value;
    m_Api_keyIsSet = true;
}
bool BasicBotBase::apiKeyIsSet() const
{
    return m_Api_keyIsSet;
}
void BasicBotBase::unsetApi_key()
{
    m_Api_keyIsSet = false;
}
std::string BasicBotBase::getDefaultSendingStream() const
{
    return m_Default_sending_stream;
}
void BasicBotBase::setDefaultSendingStream(std::string const& value)
{
    m_Default_sending_stream = value;
    m_Default_sending_streamIsSet = true;
}
bool BasicBotBase::defaultSendingStreamIsSet() const
{
    return m_Default_sending_streamIsSet;
}
void BasicBotBase::unsetDefault_sending_stream()
{
    m_Default_sending_streamIsSet = false;
}
std::string BasicBotBase::getDefaultEventsRegisterStream() const
{
    return m_Default_events_register_stream;
}
void BasicBotBase::setDefaultEventsRegisterStream(std::string const& value)
{
    m_Default_events_register_stream = value;
    m_Default_events_register_streamIsSet = true;
}
bool BasicBotBase::defaultEventsRegisterStreamIsSet() const
{
    return m_Default_events_register_streamIsSet;
}
void BasicBotBase::unsetDefault_events_register_stream()
{
    m_Default_events_register_streamIsSet = false;
}
bool BasicBotBase::isDefaultAllPublicStreams() const
{
    return m_Default_all_public_streams;
}
void BasicBotBase::setDefaultAllPublicStreams(bool const value)
{
    m_Default_all_public_streams = value;
    m_Default_all_public_streamsIsSet = true;
}
bool BasicBotBase::defaultAllPublicStreamsIsSet() const
{
    return m_Default_all_public_streamsIsSet;
}
void BasicBotBase::unsetDefault_all_public_streams()
{
    m_Default_all_public_streamsIsSet = false;
}
std::string BasicBotBase::getAvatarUrl() const
{
    return m_Avatar_url;
}
void BasicBotBase::setAvatarUrl(std::string const& value)
{
    m_Avatar_url = value;
    m_Avatar_urlIsSet = true;
}
bool BasicBotBase::avatarUrlIsSet() const
{
    return m_Avatar_urlIsSet;
}
void BasicBotBase::unsetAvatar_url()
{
    m_Avatar_urlIsSet = false;
}
int32_t BasicBotBase::getOwnerId() const
{
    return m_Owner_id;
}
void BasicBotBase::setOwnerId(int32_t const value)
{
    m_Owner_id = value;
    m_Owner_idIsSet = true;
}
bool BasicBotBase::ownerIdIsSet() const
{
    return m_Owner_idIsSet;
}
void BasicBotBase::unsetOwner_id()
{
    m_Owner_idIsSet = false;
}
std::vector<OneOfobjectobject> BasicBotBase::getServices() const
{
    return m_Services;
}
void BasicBotBase::setServices(std::vector<OneOfobjectobject> const& value)
{
    m_Services = value;
    m_ServicesIsSet = true;
}
bool BasicBotBase::servicesIsSet() const
{
    return m_ServicesIsSet;
}
void BasicBotBase::unsetServices()
{
    m_ServicesIsSet = false;
}


} // namespace org::openapitools::server::model

