# #Zulip REST API
#
##Powerful open source group chat 
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.2.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for ::InvalidApiKeyError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ::InvalidApiKeyError do

  describe "test an instance of InvalidApiKeyError" do
    it "should create an instance of InvalidApiKeyError" do
      #instance = ::InvalidApiKeyError.new
      #expect(instance).to be_instance_of(::InvalidApiKeyError)
    end
  end
  describe "test attribute 'result'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'msg'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
