# #Zulip REST API
#
##Powerful open source group chat 
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.2.0
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for ::JsonErrorBaseAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ::JsonErrorBaseAllOf do

  describe "test an instance of JsonErrorBaseAllOf" do
    it "should create an instance of JsonErrorBaseAllOf" do
      #instance = ::JsonErrorBaseAllOf.new
      #expect(instance).to be_instance_of(::JsonErrorBaseAllOf)
    end
  end
  describe "test attribute 'result'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Petstore::EnumTest::EnumAttributeValidator.new("String", ["error"])
      # validator.allowable_values.each do |value|
      #   expect { instance.result = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'msg'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
