#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Zulip REST API
* Powerful open source group chat 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIOneOfObjectObject.h"
@protocol OAIOneOfObjectObject;
@class OAIOneOfObjectObject;



@protocol OAIBasicBotBase
@end

@interface OAIBasicBotBase : OAIObject

/* The user id of the bot.  [optional]
 */
@property(nonatomic) NSNumber* userId;
/* The full name of the bot.  [optional]
 */
@property(nonatomic) NSString* fullName;
/* The API key of the bot which it uses to make API requests.  [optional]
 */
@property(nonatomic) NSString* apiKey;
/* The default sending stream of the bot. Null if the bot doesn't have a default sending stream.  [optional]
 */
@property(nonatomic) NSString* defaultSendingStream;
/* The default stream for which the bot receives events/register data. Null if the bot doesn't have such a default stream.  [optional]
 */
@property(nonatomic) NSString* defaultEventsRegisterStream;
/* Whether the bot can send messages to all streams by default.  [optional]
 */
@property(nonatomic) NSNumber* defaultAllPublicStreams;
/* The URL of the bot's avatar.  [optional]
 */
@property(nonatomic) NSString* avatarUrl;
/* The user id of the bot's owner.  Null if the bot has no owner.  [optional]
 */
@property(nonatomic) NSNumber* ownerId;
/* The \"Services\" array contains extra configuration fields only relevant for Outgoing webhook bots and Embedded bots.  It is always a single-element array.  We consider this part of the Zulip API to be unstable; it is used only for UI elements for administering bots and is likely to change.  [optional]
 */
@property(nonatomic) NSArray<OAIOneOfObjectObject>* services;

@end
