/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model


case class UserAllOf (
  email: Option[AnyType] = None,
  isBot: Option[AnyType] = None,
  avatarUrl: Option[AnyType] = None,
  avatarVersion: Option[AnyType] = None,
  fullName: Option[AnyType] = None,
  isAdmin: Option[AnyType] = None,
  isOwner: Option[AnyType] = None,
  isBillingAdmin: Option[AnyType] = None,
  role: Option[AnyType] = None,
  botType: Option[AnyType] = None,
  userId: Option[AnyType] = None,
  botOwnerId: Option[AnyType] = None,
  isActive: Option[AnyType] = None,
  isGuest: Option[AnyType] = None,
  timezone: Option[AnyType] = None,
  dateJoined: Option[AnyType] = None,
  deliveryEmail: Option[AnyType] = None,
  profileData: Option[AnyType] = None
)

