/**
* Zulip REST API
* Powerful open source group chat 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.AnyType
import org.openapitools.server.models.BasicStreamAllOf
import org.openapitools.server.models.BasicStreamBase

/**
 * 
 * @param streamId 
 * @param name 
 * @param description 
 * @param dateCreated 
 * @param inviteOnly 
 * @param renderedDescription 
 * @param isWebPublic 
 * @param streamPostPolicy 
 * @param messageRetentionDays 
 * @param historyPublicToSubscribers 
 * @param firstMessageId 
 * @param isAnnouncementOnly 
 */
data class BasicStream(
    val streamId: AnyType? = null,
    val name: AnyType? = null,
    val description: AnyType? = null,
    val dateCreated: AnyType? = null,
    val inviteOnly: AnyType? = null,
    val renderedDescription: AnyType? = null,
    val isWebPublic: AnyType? = null,
    val streamPostPolicy: AnyType? = null,
    val messageRetentionDays: AnyType? = null,
    val historyPublicToSubscribers: AnyType? = null,
    val firstMessageId: AnyType? = null,
    val isAnnouncementOnly: AnyType? = null
) 

