# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BasicStreamAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, stream_id: object=None, name: object=None, description: object=None, date_created: object=None, invite_only: object=None, rendered_description: object=None, is_web_public: object=None, stream_post_policy: object=None, message_retention_days: object=None, history_public_to_subscribers: object=None, first_message_id: object=None, is_announcement_only: object=None):
        """BasicStreamAllOf - a model defined in OpenAPI

        :param stream_id: The stream_id of this BasicStreamAllOf.
        :param name: The name of this BasicStreamAllOf.
        :param description: The description of this BasicStreamAllOf.
        :param date_created: The date_created of this BasicStreamAllOf.
        :param invite_only: The invite_only of this BasicStreamAllOf.
        :param rendered_description: The rendered_description of this BasicStreamAllOf.
        :param is_web_public: The is_web_public of this BasicStreamAllOf.
        :param stream_post_policy: The stream_post_policy of this BasicStreamAllOf.
        :param message_retention_days: The message_retention_days of this BasicStreamAllOf.
        :param history_public_to_subscribers: The history_public_to_subscribers of this BasicStreamAllOf.
        :param first_message_id: The first_message_id of this BasicStreamAllOf.
        :param is_announcement_only: The is_announcement_only of this BasicStreamAllOf.
        """
        self.openapi_types = {
            'stream_id': object,
            'name': object,
            'description': object,
            'date_created': object,
            'invite_only': object,
            'rendered_description': object,
            'is_web_public': object,
            'stream_post_policy': object,
            'message_retention_days': object,
            'history_public_to_subscribers': object,
            'first_message_id': object,
            'is_announcement_only': object
        }

        self.attribute_map = {
            'stream_id': 'stream_id',
            'name': 'name',
            'description': 'description',
            'date_created': 'date_created',
            'invite_only': 'invite_only',
            'rendered_description': 'rendered_description',
            'is_web_public': 'is_web_public',
            'stream_post_policy': 'stream_post_policy',
            'message_retention_days': 'message_retention_days',
            'history_public_to_subscribers': 'history_public_to_subscribers',
            'first_message_id': 'first_message_id',
            'is_announcement_only': 'is_announcement_only'
        }

        self._stream_id = stream_id
        self._name = name
        self._description = description
        self._date_created = date_created
        self._invite_only = invite_only
        self._rendered_description = rendered_description
        self._is_web_public = is_web_public
        self._stream_post_policy = stream_post_policy
        self._message_retention_days = message_retention_days
        self._history_public_to_subscribers = history_public_to_subscribers
        self._first_message_id = first_message_id
        self._is_announcement_only = is_announcement_only

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BasicStreamAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BasicStream_allOf of this BasicStreamAllOf.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stream_id(self):
        """Gets the stream_id of this BasicStreamAllOf.


        :return: The stream_id of this BasicStreamAllOf.
        :rtype: object
        """
        return self._stream_id

    @stream_id.setter
    def stream_id(self, stream_id):
        """Sets the stream_id of this BasicStreamAllOf.


        :param stream_id: The stream_id of this BasicStreamAllOf.
        :type stream_id: object
        """

        self._stream_id = stream_id

    @property
    def name(self):
        """Gets the name of this BasicStreamAllOf.


        :return: The name of this BasicStreamAllOf.
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BasicStreamAllOf.


        :param name: The name of this BasicStreamAllOf.
        :type name: object
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this BasicStreamAllOf.


        :return: The description of this BasicStreamAllOf.
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BasicStreamAllOf.


        :param description: The description of this BasicStreamAllOf.
        :type description: object
        """

        self._description = description

    @property
    def date_created(self):
        """Gets the date_created of this BasicStreamAllOf.


        :return: The date_created of this BasicStreamAllOf.
        :rtype: object
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this BasicStreamAllOf.


        :param date_created: The date_created of this BasicStreamAllOf.
        :type date_created: object
        """

        self._date_created = date_created

    @property
    def invite_only(self):
        """Gets the invite_only of this BasicStreamAllOf.


        :return: The invite_only of this BasicStreamAllOf.
        :rtype: object
        """
        return self._invite_only

    @invite_only.setter
    def invite_only(self, invite_only):
        """Sets the invite_only of this BasicStreamAllOf.


        :param invite_only: The invite_only of this BasicStreamAllOf.
        :type invite_only: object
        """

        self._invite_only = invite_only

    @property
    def rendered_description(self):
        """Gets the rendered_description of this BasicStreamAllOf.


        :return: The rendered_description of this BasicStreamAllOf.
        :rtype: object
        """
        return self._rendered_description

    @rendered_description.setter
    def rendered_description(self, rendered_description):
        """Sets the rendered_description of this BasicStreamAllOf.


        :param rendered_description: The rendered_description of this BasicStreamAllOf.
        :type rendered_description: object
        """

        self._rendered_description = rendered_description

    @property
    def is_web_public(self):
        """Gets the is_web_public of this BasicStreamAllOf.


        :return: The is_web_public of this BasicStreamAllOf.
        :rtype: object
        """
        return self._is_web_public

    @is_web_public.setter
    def is_web_public(self, is_web_public):
        """Sets the is_web_public of this BasicStreamAllOf.


        :param is_web_public: The is_web_public of this BasicStreamAllOf.
        :type is_web_public: object
        """

        self._is_web_public = is_web_public

    @property
    def stream_post_policy(self):
        """Gets the stream_post_policy of this BasicStreamAllOf.


        :return: The stream_post_policy of this BasicStreamAllOf.
        :rtype: object
        """
        return self._stream_post_policy

    @stream_post_policy.setter
    def stream_post_policy(self, stream_post_policy):
        """Sets the stream_post_policy of this BasicStreamAllOf.


        :param stream_post_policy: The stream_post_policy of this BasicStreamAllOf.
        :type stream_post_policy: object
        """

        self._stream_post_policy = stream_post_policy

    @property
    def message_retention_days(self):
        """Gets the message_retention_days of this BasicStreamAllOf.


        :return: The message_retention_days of this BasicStreamAllOf.
        :rtype: object
        """
        return self._message_retention_days

    @message_retention_days.setter
    def message_retention_days(self, message_retention_days):
        """Sets the message_retention_days of this BasicStreamAllOf.


        :param message_retention_days: The message_retention_days of this BasicStreamAllOf.
        :type message_retention_days: object
        """

        self._message_retention_days = message_retention_days

    @property
    def history_public_to_subscribers(self):
        """Gets the history_public_to_subscribers of this BasicStreamAllOf.


        :return: The history_public_to_subscribers of this BasicStreamAllOf.
        :rtype: object
        """
        return self._history_public_to_subscribers

    @history_public_to_subscribers.setter
    def history_public_to_subscribers(self, history_public_to_subscribers):
        """Sets the history_public_to_subscribers of this BasicStreamAllOf.


        :param history_public_to_subscribers: The history_public_to_subscribers of this BasicStreamAllOf.
        :type history_public_to_subscribers: object
        """

        self._history_public_to_subscribers = history_public_to_subscribers

    @property
    def first_message_id(self):
        """Gets the first_message_id of this BasicStreamAllOf.


        :return: The first_message_id of this BasicStreamAllOf.
        :rtype: object
        """
        return self._first_message_id

    @first_message_id.setter
    def first_message_id(self, first_message_id):
        """Sets the first_message_id of this BasicStreamAllOf.


        :param first_message_id: The first_message_id of this BasicStreamAllOf.
        :type first_message_id: object
        """

        self._first_message_id = first_message_id

    @property
    def is_announcement_only(self):
        """Gets the is_announcement_only of this BasicStreamAllOf.


        :return: The is_announcement_only of this BasicStreamAllOf.
        :rtype: object
        """
        return self._is_announcement_only

    @is_announcement_only.setter
    def is_announcement_only(self, is_announcement_only):
        """Sets the is_announcement_only of this BasicStreamAllOf.


        :param is_announcement_only: The is_announcement_only of this BasicStreamAllOf.
        :type is_announcement_only: object
        """

        self._is_announcement_only = is_announcement_only
