# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RealmDomain(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, domain: str=None, allow_subdomains: bool=None):
        """RealmDomain - a model defined in OpenAPI

        :param domain: The domain of this RealmDomain.
        :param allow_subdomains: The allow_subdomains of this RealmDomain.
        """
        self.openapi_types = {
            'domain': str,
            'allow_subdomains': bool
        }

        self.attribute_map = {
            'domain': 'domain',
            'allow_subdomains': 'allow_subdomains'
        }

        self._domain = domain
        self._allow_subdomains = allow_subdomains

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RealmDomain':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RealmDomain of this RealmDomain.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain(self):
        """Gets the domain of this RealmDomain.

        The new allowed domain. 

        :return: The domain of this RealmDomain.
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this RealmDomain.

        The new allowed domain. 

        :param domain: The domain of this RealmDomain.
        :type domain: str
        """

        self._domain = domain

    @property
    def allow_subdomains(self):
        """Gets the allow_subdomains of this RealmDomain.

        Whether subdomains are allowed for this domain. 

        :return: The allow_subdomains of this RealmDomain.
        :rtype: bool
        """
        return self._allow_subdomains

    @allow_subdomains.setter
    def allow_subdomains(self, allow_subdomains):
        """Sets the allow_subdomains of this RealmDomain.

        Whether subdomains are allowed for this domain. 

        :param allow_subdomains: The allow_subdomains of this RealmDomain.
        :type allow_subdomains: bool
        """

        self._allow_subdomains = allow_subdomains
