/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddSubscriptionsResponse {
  result: any;
  msg: any;
  /**
   * A dictionary where the key is the email address of the user/bot and the value is a list of the names of the streams that were subscribed to as a result of the query. 
   */
  subscribed?: { [key: string]: Array<string>; };
  /**
   * A dictionary where the key is the email address of the user/bot and the value is a list of the names of the streams that the user/bot is already subscribed to. 
   */
  already_subscribed?: { [key: string]: Array<string>; };
  /**
   * A list of names of streams that the requesting user/bot was not authorized to subscribe to.  Only present if `authorization_errors_fatal=false`. 
   */
  unauthorized?: Array<string>;
}


export interface AddSubscriptionsResponseAllOf {
  result?: any;
  msg?: any;
  /**
   * A dictionary where the key is the email address of the user/bot and the value is a list of the names of the streams that were subscribed to as a result of the query. 
   */
  subscribed?: { [key: string]: Array<string>; };
  /**
   * A dictionary where the key is the email address of the user/bot and the value is a list of the names of the streams that the user/bot is already subscribed to. 
   */
  already_subscribed?: { [key: string]: Array<string>; };
  /**
   * A list of names of streams that the requesting user/bot was not authorized to subscribe to.  Only present if `authorization_errors_fatal=false`. 
   */
  unauthorized?: Array<string>;
}


export interface ApiKeyResponse {
  result: any;
  msg: any;
  /**
   * The API key that can be used to authenticate as the requested user. 
   */
  api_key: string;
  /**
   * The email address of the user who owns the API key 
   */
  email: string;
}


export interface ApiKeyResponseAllOf {
  result?: any;
  msg?: any;
  /**
   * The API key that can be used to authenticate as the requested user. 
   */
  api_key: string;
  /**
   * The email address of the user who owns the API key 
   */
  email: string;
}


/**
 * Dictionary containing details of a file uploaded by a user. 
 */
export interface Attachments {
  /**
   * The unique ID for the attachment. 
   */
  id?: number;
  /**
   * Name of the uploaded file. 
   */
  name?: string;
  /**
   * A representation of the path of the file within the repository of user-uploaded files.  If the `path_id` of a file is `{realm_id}/ab/cdef/temp_file.py`, its URL will be: `{server_url}/user_uploads/{realm_id}/ab/cdef/temp_file.py`. 
   */
  path_id?: string;
  /**
   * Size of the file in bytes. 
   */
  size?: number;
  /**
   * Time when the attachment was uploaded as a UNIX timestamp multiplied by 1000 (matching the format of getTime() in JavaScript).  **Changes**: Changed in Zulip 2.2 (feature level 22).  This field was previously a floating point number. 
   */
  create_time?: number;
  /**
   * Contains basic details on any Zulip messages that have been sent referencing this [uploaded file](/api/upload-file). This includes messages sent by any user in the Zulip organization who sent a message containing a link to the uploaded file. 
   */
  messages?: Array<AttachmentsMessages>;
}


export interface AttachmentsMessages {
  /**
   * Time when the message was sent as a UNIX timestamp multiplied by 1000 (matching the format of getTime() in JavaScript).  **Changes**: Changed in Zulip 2.2 (feature level 22).  This field was previously strangely called `name` and was a floating point number. 
   */
  date_sent?: number;
  /**
   * The unique message ID.  Messages should always be displayed sorted by ID. 
   */
  id?: number;
}


export interface BadEventQueueIdError {
  result: any;
  msg: any;
  code?: any;
  /**
   * The string that identifies the invalid event queue. 
   */
  queue_id?: string;
}


export interface BadEventQueueIdErrorAllOf {
  result?: any;
  msg?: any;
  code?: any;
  /**
   * The string that identifies the invalid event queue. 
   */
  queue_id?: string;
}


export interface BasicBot {
  user_id?: any;
  full_name?: any;
  api_key?: any;
  default_sending_stream?: any;
  default_events_register_stream?: any;
  default_all_public_streams?: any;
  avatar_url?: any;
  owner_id?: any;
  services?: any;
}


export interface BasicBotAllOf {
  user_id?: any;
  full_name?: any;
  api_key?: any;
  default_sending_stream?: any;
  default_events_register_stream?: any;
  default_all_public_streams?: any;
  avatar_url?: any;
  owner_id?: any;
  services?: any;
}


export interface BasicBotBase {
  /**
   * The user id of the bot. 
   */
  user_id?: number;
  /**
   * The full name of the bot. 
   */
  full_name?: string;
  /**
   * The API key of the bot which it uses to make API requests. 
   */
  api_key?: string;
  /**
   * The default sending stream of the bot. Null if the bot doesn\'t have a default sending stream. 
   */
  default_sending_stream?: string;
  /**
   * The default stream for which the bot receives events/register data. Null if the bot doesn\'t have such a default stream. 
   */
  default_events_register_stream?: string;
  /**
   * Whether the bot can send messages to all streams by default. 
   */
  default_all_public_streams?: boolean;
  /**
   * The URL of the bot\'s avatar. 
   */
  avatar_url?: string;
  /**
   * The user id of the bot\'s owner.  Null if the bot has no owner. 
   */
  owner_id?: number;
  /**
   * The \"Services\" array contains extra configuration fields only relevant for Outgoing webhook bots and Embedded bots.  It is always a single-element array.  We consider this part of the Zulip API to be unstable; it is used only for UI elements for administering bots and is likely to change. 
   */
  services?: Array<object>;
}


export interface BasicStream {
  stream_id?: any;
  name?: any;
  description?: any;
  date_created?: any;
  invite_only?: any;
  rendered_description?: any;
  is_web_public?: any;
  stream_post_policy?: any;
  message_retention_days?: any;
  history_public_to_subscribers?: any;
  first_message_id?: any;
  is_announcement_only?: any;
}


export interface BasicStreamAllOf {
  stream_id?: any;
  name?: any;
  description?: any;
  date_created?: any;
  invite_only?: any;
  rendered_description?: any;
  is_web_public?: any;
  stream_post_policy?: any;
  message_retention_days?: any;
  history_public_to_subscribers?: any;
  first_message_id?: any;
  is_announcement_only?: any;
}


/**
 * Object containing basic details about the stream. 
 */
export interface BasicStreamBase {
  /**
   * The unique ID of the stream. 
   */
  stream_id?: number;
  /**
   * The name of the stream. 
   */
  name?: string;
  /**
   * The short description of the stream in text/markdown format, intended to be used to prepopulate UI for editing a stream\'s description. 
   */
  description?: string;
  /**
   * The UNIX timestamp for when the stream was created, in UTC seconds.  **Changes**: New in Zulip 4.0 (feature level 30). 
   */
  date_created?: number;
  /**
   * Specifies whether the stream is private or not. Only people who have been invited can access a private stream. 
   */
  invite_only?: boolean;
  /**
   * The short description of the stream rendered as HTML, intended to be used when displaying the stream description in a UI.  One should use the standard Zulip rendered_markdown CSS when displaying this content so that emoji, LaTeX, and other syntax work correctly.  And any client-side security logic for user-generated message content should be applied when displaying this HTML as though it were the body of a Zulip message. 
   */
  rendered_description?: string;
  /**
   * Whether the stream has been configured to allow unauthenticated access to its message history from the web. 
   */
  is_web_public?: boolean;
  /**
   * Policy for which users can post messages to the stream.  * 1 => Any user can post. * 2 => Only administrators can post. * 3 => Only full members can post. * 4 => Only moderators can post.  **Changes**: New in Zulip 3.0, replacing the previous `is_announcement_only` boolean. 
   */
  stream_post_policy?: number;
  /**
   * Number of days that messages sent to this stream will be stored before being automatically deleted by the [message retention policy](/help/message-retention-policy).  There are two special values:  * `null`, the default, means the stream will inherit the organization   level setting. * `-1` encodes retaining messages in this stream forever.  **Changes**: New in Zulip 3.0 (feature level 17). 
   */
  message_retention_days?: number;
  /**
   * Whether the history of the stream is public to its subscribers.  Currently always true for public streams (i.e. invite_only=False implies history_public_to_subscribers=True), but clients should not make that assumption, as we may change that behavior in the future. 
   */
  history_public_to_subscribers?: boolean;
  /**
   * The id of the first message in the stream.  Intended to help clients determine whether they need to display UI like the \"more topics\" widget that would suggest the stream has older history that can be accessed.  Null is used for streams with no message history. 
   */
  first_message_id?: number;
  /**
   * Whether the given stream is announcement only or not.  **Changes**: Deprecated in Zulip 3.0 (feature level 1), use `stream_post_policy` instead. 
   */
  is_announcement_only?: boolean;
}


export interface Bot {
  user_id?: any;
  full_name?: any;
  api_key?: any;
  default_sending_stream?: any;
  default_events_register_stream?: any;
  default_all_public_streams?: any;
  avatar_url?: any;
  owner_id?: any;
  services?: any;
  /**
   * The email of the bot. 
   */
  email?: string;
  /**
   * An integer describing the type of bot: * `1` for a `Generic` bot. * `2` for an `Incoming webhook` bot. * `3` for an `Outgoing webhook` bot. * `4` for an `Embedded` bot. 
   */
  bot_type?: number;
  /**
   * A boolean describing whether the user account has been deactivated. 
   */
  is_active?: boolean;
}


/**
 * Object containing details of a bot. 
 */
export interface BotAllOf {
  user_id?: any;
  full_name?: any;
  api_key?: any;
  default_sending_stream?: any;
  default_events_register_stream?: any;
  default_all_public_streams?: any;
  avatar_url?: any;
  owner_id?: any;
  services?: any;
  /**
   * The email of the bot. 
   */
  email?: string;
  /**
   * An integer describing the type of bot: * `1` for a `Generic` bot. * `2` for an `Incoming webhook` bot. * `3` for an `Outgoing webhook` bot. * `4` for an `Embedded` bot. 
   */
  bot_type?: number;
  /**
   * A boolean describing whether the user account has been deactivated. 
   */
  is_active?: boolean;
}


export interface CodedError {
  result: any;
  msg: any;
  code?: any;
}


export interface CodedErrorAllOf {
  result?: any;
  msg?: any;
  code?: any;
}


export interface CodedErrorBase {
  result: any;
  msg: any;
  /**
   * A string that identifies the error. 
   */
  code?: string;
}


export interface CodedErrorBaseAllOf {
  result?: any;
  msg?: any;
  /**
   * A string that identifies the error. 
   */
  code?: string;
}


/**
 * Dictionary containing the details of a custom profile field configured for this organization. 
 */
export interface CustomProfileField {
  /**
   * The ID of the custom profile field.  This will be referenced in custom the profile fields section of user objects. 
   */
  id?: number;
  /**
   * An integer indicating the type of the custom profile field, which determines how it is configured and displayed to users.  See the [Add custom profile fields](/help/add-custom-profile-fields) article for details on what each type means.  * **1**: Short text * **2**: Long text * **3**: List of options * **4**: Date picker * **5**: Link * **6**: Person picker * **7**: External account 
   */
  type?: number;
  /**
   * Custom profile fields are displayed in both settings UI and UI showing users\' profiles in increasing `order`. 
   */
  order?: number;
  /**
   * The name of the custom profile field. 
   */
  name?: string;
  /**
   * The help text to be displayed for the custom profile field in user-facing settings UI for configuring custom profile fields. 
   */
  hint?: string;
  /**
   * Field types 3 (List of options) and 7 (External account) support storing additional configuration for the field type in the `field_data` attribute.  For field type 3 (List of options), this attribute is a JSON dictionary defining the choices and the order they will be displayed in the dropdown UI for individual users to select an option.  The interface for field type 7 is not yet stabilized. 
   */
  field_data?: string;
}


/**
 * Dictionary containing details of a default stream group. 
 */
export interface DefaultStreamGroup {
  /**
   * Name of the default stream group. 
   */
  name?: string;
  /**
   * Description of the default stream group. 
   */
  description?: string;
  /**
   * id of the default stream group. 
   */
  id?: number;
  /**
   * Array containing details about the streams in the default stream group. 
   */
  streams?: Array<BasicStream>;
}


/**
 * A dictionary for representing a message draft. 
 */
export interface Draft {
  /**
   * The unique ID of the draft. It will only used whenever the drafts are fetched. This field should not be specified when the draft is being created or edited. 
   */
  id?: number;
  /**
   * The type of the draft. Either unaddressed (empty string), \"stream\", or \"private\" (for PMs and private group messages). 
   */
  type: DraftTypeEnum;
  /**
   * An array of the tentative target audience IDs. For \"stream\" messages, this should contain exactly 1 ID, the ID of the target stream. For private messages, this should be an array of target user IDs. For unaddressed drafts, this is ignored, and clients should send an empty array. 
   */
  to: Array<number>;
  /**
   * For stream message drafts, the tentative topic name. For private or unaddressed messages, this will be ignored and should ideally be the empty string. Should not contain null bytes. 
   */
  topic: string;
  /**
   * The body of the draft. Should not contain null bytes. 
   */
  content: string;
  /**
   * A Unix timestamp (seconds only) representing when the draft was last edited. When creating a draft, this key need not be present and it will be filled in automatically by the server. 
   */
  timestamp?: number;
}

/**
 * Enum for the type property.
 */
export type DraftTypeEnum = '' | 'stream' | 'private';


export interface EmojiBase {
  /**
   * A unique identifier, defining the specific emoji codepoint requested, within the namespace of the `reaction_type`.  For example, for `unicode_emoji`, this will be an encoding of the Unicode codepoint; for `realm_emoji`, it\'ll be the ID of the realm emoji. 
   */
  emoji_code?: string;
  /**
   * Name of the emoji. 
   */
  emoji_name?: string;
  /**
   * One of the following values:  * `unicode_emoji`: Unicode emoji (`emoji_code` will be its Unicode   codepoint). * `realm_emoji`: [Custom emoji](/help/add-custom-emoji).   (`emoji_code` will be its ID). * `zulip_extra_emoji`: Special emoji included with Zulip.  Exists to   namespace the `zulip` emoji. 
   */
  reaction_type?: string;
}


export interface EmojiReaction {
  emoji_code?: any;
  emoji_name?: any;
  reaction_type?: any;
  user_id?: any;
  user?: any;
}


export interface EmojiReactionAllOf {
  emoji_code?: any;
  emoji_name?: any;
  reaction_type?: any;
  user_id?: any;
  user?: any;
}


export interface EmojiReactionBase {
  /**
   * A unique identifier, defining the specific emoji codepoint requested, within the namespace of the `reaction_type`.  For example, for `unicode_emoji`, this will be an encoding of the Unicode codepoint; for `realm_emoji`, it\'ll be the ID of the realm emoji. 
   */
  emoji_code?: string;
  /**
   * Name of the emoji. 
   */
  emoji_name?: string;
  /**
   * One of the following values:  * `unicode_emoji`: Unicode emoji (`emoji_code` will be its Unicode   codepoint). * `realm_emoji`: [Custom emoji](/help/add-custom-emoji).   (`emoji_code` will be its ID). * `zulip_extra_emoji`: Special emoji included with Zulip.  Exists to   namespace the `zulip` emoji. 
   */
  reaction_type?: string;
  /**
   * The ID of the user who added the reaction.  **Changes**: New in Zulip 3.0 (feature level 2). The `user` object is deprecated and will be removed in the future. 
   */
  user_id?: number;
  user?: EmojiReactionBaseAllOfUser;
}


export interface EmojiReactionBaseAllOf {
  /**
   * The ID of the user who added the reaction.  **Changes**: New in Zulip 3.0 (feature level 2). The `user` object is deprecated and will be removed in the future. 
   */
  user_id?: number;
  user?: EmojiReactionBaseAllOfUser;
}


/**
 * Whether the user is a mirror dummy. Dictionary with data on the user who added the reaction, including the user ID as the `id` field.  **Note**: In the [events API](/api/get-events), this `user` dictionary confusing had the user ID in a field called `user_id` instead.  We recommend ignoring fields other than the user ID.  **Deprecated** and to be removed in a future release once core clients have migrated to use the `user_id` field. 
 */
export interface EmojiReactionBaseAllOfUser {
  /**
   * ID of the user. 
   */
  id?: number;
  /**
   * Email of the user. 
   */
  email?: string;
  /**
   * Full name of the user. 
   */
  full_name?: string;
  /**
   * Whether the user is a mirror dummy. 
   */
  is_mirror_dummy?: boolean;
}


export interface GetMessages {
  avatar_url?: any;
  client?: any;
  content?: any;
  content_type?: any;
  display_recipient?: any;
  id?: any;
  is_me_message?: any;
  reactions?: any;
  recipient_id?: any;
  sender_email?: any;
  sender_full_name?: any;
  sender_id?: any;
  sender_realm_str?: any;
  stream_id?: any;
  subject?: any;
  topic_links?: any;
  submessages?: any;
  timestamp?: any;
  type?: any;
  /**
   * The user\'s [message flags][message-flags] for the message.  [message-flags]: /api/update-message-flags#available-flags 
   */
  flags?: Array<string>;
  /**
   * The UNIX timestamp for when the message was last edited, in UTC seconds. 
   */
  last_edit_timestamp?: number;
  /**
   * Only present if keyword search was included among the narrow parameters. HTML content of a queried message that matches the narrow, with `<span class=\"highlight\">` elements wrapping the matches for the search keywords. 
   */
  match_content?: string;
  /**
   * Only present if keyword search was included among the narrow parameters. HTML-escaped topic of a queried message that matches the narrow, with `<span class=\"highlight\">` elements wrapping the matches for the search keywords. 
   */
  match_subject?: string;
}


export interface GetMessagesAllOf {
  avatar_url?: any;
  client?: any;
  content?: any;
  content_type?: any;
  display_recipient?: any;
  id?: any;
  is_me_message?: any;
  reactions?: any;
  recipient_id?: any;
  sender_email?: any;
  sender_full_name?: any;
  sender_id?: any;
  sender_realm_str?: any;
  stream_id?: any;
  subject?: any;
  topic_links?: any;
  submessages?: any;
  timestamp?: any;
  type?: any;
  /**
   * The user\'s [message flags][message-flags] for the message.  [message-flags]: /api/update-message-flags#available-flags 
   */
  flags?: Array<string>;
  /**
   * The UNIX timestamp for when the message was last edited, in UTC seconds. 
   */
  last_edit_timestamp?: number;
  /**
   * Only present if keyword search was included among the narrow parameters. HTML content of a queried message that matches the narrow, with `<span class=\"highlight\">` elements wrapping the matches for the search keywords. 
   */
  match_content?: string;
  /**
   * Only present if keyword search was included among the narrow parameters. HTML-escaped topic of a queried message that matches the narrow, with `<span class=\"highlight\">` elements wrapping the matches for the search keywords. 
   */
  match_subject?: string;
}


/**
 * Dictionary containing details of a single hotspot. 
 */
export interface Hotspot {
  /**
   * The delay after which the user should be shown the hotspot. 
   */
  delay?: number;
  /**
   * The name of the hotspot. 
   */
  name?: string;
  /**
   * The title of the hotspot, as will be displayed to the user. 
   */
  title?: string;
  /**
   * The description of the hotspot, as will be displayed to the user. 
   */
  description?: string;
}


/**
 * This is an example of the JSON payload that the Zulip server will `POST` to your server 
 */
export interface InlineResponse200 {
  /**
   * Email of the bot user. 
   */
  bot_email?: string;
  /**
   * The full name of the bot user. 
   */
  bot_full_name?: string;
  /**
   * The message content, in raw Markdown format (not rendered to HTML). 
   */
  data?: string;
  /**
   * What aspect of the message triggered the outgoing webhook notification. Possible values include `private_message` and `mention`. 
   */
  trigger?: string;
  /**
   * A string of alphanumeric characters that can be used to authenticate the webhook request (each bot user uses a fixed token). You can get the token used by a given outgoing webhook bot in the `zuliprc` file downloaded when creating the bot. 
   */
  token?: string;
  /**
   * A dict containing details on the message that triggered the outgoing webhook, in the format used by [`GET /messages`](/api/get-messages). 
   */
  message?: MessagesBase & object;
}


export interface InvalidApiKeyError {
  result: any;
  msg: any;
}


export interface InvalidMessageError {
  result: any;
  msg: any;
  /**
   * The raw content of the message. 
   */
  raw_content?: string;
}


export interface InvalidMessageErrorAllOf {
  result?: any;
  msg?: any;
  /**
   * The raw content of the message. 
   */
  raw_content?: string;
}


export interface JsonError {
  result: any;
  msg: any;
}


export interface JsonErrorBase {
  result: JsonErrorBaseResultEnum;
  msg: string;
}

/**
 * Enum for the result property.
 */
export type JsonErrorBaseResultEnum = 'error';


export interface JsonErrorBaseAllOf {
  result: JsonErrorBaseAllOfResultEnum;
  msg: string;
}

/**
 * Enum for the result property.
 */
export type JsonErrorBaseAllOfResultEnum = 'error';


export interface JsonResponseBase {
  result?: string;
}


export interface JsonSuccess {
  result: any;
  msg: any;
}


export interface JsonSuccessAllOf {
  result?: any;
  msg?: any;
}


export interface JsonSuccessBase {
  result: JsonSuccessBaseResultEnum;
  msg: string;
}

/**
 * Enum for the result property.
 */
export type JsonSuccessBaseResultEnum = 'success';


export interface JsonSuccessBaseAllOf {
  result: JsonSuccessBaseAllOfResultEnum;
  msg: string;
}

/**
 * Enum for the result property.
 */
export type JsonSuccessBaseAllOfResultEnum = 'success';


export interface Messages {
  avatar_url?: any;
  client?: any;
  content?: any;
  content_type?: any;
  display_recipient?: any;
  id?: any;
  is_me_message?: any;
  reactions?: any;
  recipient_id?: any;
  sender_email?: any;
  sender_full_name?: any;
  sender_id?: any;
  sender_realm_str?: any;
  stream_id?: any;
  subject?: any;
  topic_links?: any;
  submessages?: any;
  timestamp?: any;
  type?: any;
}


export interface MessagesAllOf {
  avatar_url?: any;
  client?: any;
  content?: any;
  content_type?: any;
  display_recipient?: any;
  id?: any;
  is_me_message?: any;
  reactions?: any;
  recipient_id?: any;
  sender_email?: any;
  sender_full_name?: any;
  sender_id?: any;
  sender_realm_str?: any;
  stream_id?: any;
  subject?: any;
  topic_links?: any;
  submessages?: any;
  timestamp?: any;
  type?: any;
}


/**
 * Object containing details of the message. 
 */
export interface MessagesBase {
  /**
   * The URL of the user\'s avatar.  Can be null only if client_gravatar was passed, which means that the user has not uploaded an avatar in Zulip, and the client should compute the gravatar URL by hashing the user\'s email address itself for this user. 
   */
  avatar_url?: string;
  /**
   * A Zulip \"client\" string, describing what Zulip client sent the message. 
   */
  client?: string;
  /**
   * The content/body of the message. 
   */
  content?: string;
  /**
   * The HTTP `content_type` for the message content.  This will be `text/html` or `text/x-markdown`, depending on whether `apply_markdown` was set. 
   */
  content_type?: string;
  /**
   * Data on the recipient of the message; either the name of a stream or a dictionary containing basic data on the users who received the message. 
   */
  display_recipient?: string | Array<object>;
  /**
   * The unique message ID.  Messages should always be displayed sorted by ID. 
   */
  id?: number;
  /**
   * Whether the message is a [/me status message][status-messages]  [status-messages]: /help/format-your-message-using-markdown#status-messages 
   */
  is_me_message?: boolean;
  /**
   * Data on any reactions to the message. 
   */
  reactions?: Array<EmojiReaction>;
  /**
   * A unique ID for the set of users receiving the message (either a stream or group of users).  Useful primarily for hashing. 
   */
  recipient_id?: number;
  /**
   * The Zulip display email address of the message\'s sender. 
   */
  sender_email?: string;
  /**
   * The full name of the message\'s sender. 
   */
  sender_full_name?: string;
  /**
   * The user ID of the message\'s sender. 
   */
  sender_id?: number;
  /**
   * A string identifier for the realm the sender is in.  Unique only within the context of a given Zulip server.  E.g. on `example.zulip.com`, this will be `example`. 
   */
  sender_realm_str?: string;
  /**
   * Only present for stream messages; the ID of the stream. 
   */
  stream_id?: number;
  /**
   * The `topic` of the message.  Currently always `\"\"` for private messages, though this could change if Zulip adds support for topics in private message conversations.  The field name is a legacy holdover from when topics were called \"subjects\" and will eventually change. 
   */
  subject?: string;
  /**
   * Data on any links to be included in the `topic` line (these are generated by [custom linkification filters](/help/add-a-custom-linkifier) that match content in the message\'s topic.)  **Changes**: This field contained a list of urls before   Zulip 4.0 (feature level 46).  New in Zulip 3.0 (feature level 1): Previously, this field was called `subject_links`; clients are recommended to rename `subject_links` to `topic_links` if present for compatibility with older Zulip servers. 
   */
  topic_links?: Array<MessagesBaseTopicLinks>;
  /**
   * Data used for certain experimental Zulip integrations. 
   */
  submessages?: Array<string>;
  /**
   * The UNIX timestamp for when the message was sent, in UTC seconds. 
   */
  timestamp?: number;
  /**
   * The type of the message: `stream` or `private`. 
   */
  type?: string;
}


export interface MessagesBaseTopicLinks {
  /**
   * The original link text present in the topic. 
   */
  text?: string;
  /**
   * The expanded target url which the link points to. 
   */
  url?: string;
}


export interface MissingArgumentError {
  result: any;
  msg: any;
  code?: any;
  /**
   * It contains the information about the missing parameter. 
   */
  var_name?: string;
}


/**
 * ## Missing request parameter(s)  A typical failed JSON response for when a required request parameter is not supplied 
 */
export interface MissingArgumentErrorAllOf {
  result?: any;
  msg?: any;
  code?: any;
  /**
   * It contains the information about the missing parameter. 
   */
  var_name?: string;
}


export interface NonExistingStreamError {
  result: any;
  msg: any;
  code?: any;
  /**
   * The name of the stream that could not be found. 
   */
  stream?: string;
}


export interface NonExistingStreamErrorAllOf {
  result?: any;
  msg?: any;
  code?: any;
  /**
   * The name of the stream that could not be found. 
   */
  stream?: string;
}


/**
 * `{client_name}`: Object containing the details of the user\'s presence on a particular platform with the client\'s platform name being the object key. 
 */
export interface Presence {
  /**
   * The client\'s platform name. 
   */
  client?: string;
  /**
   * The status of the user on this client. It is either `idle` or `active`. 
   */
  status?: PresenceStatusEnum;
  /**
   * The UNIX timestamp of when this client sent the user\'s presence to the server with the precision of a second. 
   */
  timestamp?: number;
  /**
   * Whether the client is capable of showing mobile/push notifications to the user. 
   */
  pushable?: boolean;
}

/**
 * Enum for the status property.
 */
export type PresenceStatusEnum = 'idle' | 'active';


export interface RateLimitedError {
  result: any;
  msg: any;
  code?: any;
}


export interface RealmDeactivatedError {
  result: any;
  msg: any;
  code?: any;
}


/**
 * Object containing details of the newly added domain. 
 */
export interface RealmDomain {
  /**
   * The new allowed domain. 
   */
  domain?: string;
  /**
   * Whether subdomains are allowed for this domain. 
   */
  allow_subdomains?: boolean;
}


/**
 * `{emoji_id}`: Object containing details about the emoji with  the specified ID. It has the following properties: 
 */
export interface RealmEmoji {
  /**
   * The ID for this emoji, same as the object\'s key. 
   */
  id?: string;
  /**
   * The user-friendly name for this emoji. Users in the organization can use this emoji by writing this name between colons (`:name  :`). 
   */
  name?: string;
  /**
   * The path relative to the organization\'s URL where the emoji\'s image can be found. 
   */
  source_url?: string;
  /**
   * Whether the emoji has been deactivated or not. 
   */
  deactivated?: boolean;
  /**
   * The user ID of the user who uploaded the custom emoji. Will be null if the uploader is unknown.  **Changes**: New in Zulip 3.0 (feature level 7).  Previously was accessible via and `author` object with an `id` field. 
   */
  author_id?: number;
}


/**
 * Object containing details about a realm export. 
 */
export interface RealmExport {
  /**
   * The id of the export. 
   */
  id?: number;
  /**
   * The id of the user who did the export. 
   */
  acting_user_id?: number;
  /**
   * The UNIX timestamp of when the export was made. 
   */
  export_time?: number;
  /**
   * The timestamp of when the export was deleted. Null if it wasn\'t. 
   */
  deleted_timestamp?: number;
  /**
   * The timestamp of when the export failed. Null if it didn\'t. 
   */
  failed_timestamp?: number;
  /**
   * The URL of the export. `null` if there\'s no URL. 
   */
  export_url?: string;
  /**
   * Whether the export is pending or not. 
   */
  pending?: boolean;
}


/**
 * Object containing details about a realm playground. 
 */
export interface RealmPlayground {
  /**
   * The unique ID for the realm playground. 
   */
  id?: number;
  /**
   * The user-visible display name of the playground.  Clients should display this in UI for picking which playground to open a code block in, to differentiate between multiple configured playground options for a given pygments language.  **Changes**: New in Zulip 4.0 (feature level 49). 
   */
  name?: string;
  /**
   * The name of the Pygments language lexer for that programming language. 
   */
  pygments_language?: string;
  /**
   * The url prefix for the playground. 
   */
  url_prefix?: string;
}


export interface Subscriptions {
  /**
   * The unique ID of a stream. 
   */
  stream_id?: number;
  /**
   * The name of a stream. 
   */
  name?: string;
  /**
   * The short description of a stream in text/markdown format, intended to be used to prepopulate UI for editing a stream\'s description. 
   */
  description?: string;
  /**
   * A short description of a stream rendered as HTML, intended to be used when displaying the stream description in a UI.  One should use the standard Zulip rendered_markdown CSS when displaying this content so that emoji, LaTeX, and other syntax work correctly.  And any client-side security logic for user-generated message content should be applied when displaying this HTML as though it were the body of a Zulip message. 
   */
  rendered_description?: string;
  /**
   * The UNIX timestamp for when the stream was created, in UTC seconds.  **Changes**: New in Zulip 4.0 (feature level 30). 
   */
  date_created?: number;
  /**
   * Specifies whether the stream is private or not. Only people who have been invited can access a private stream. 
   */
  invite_only?: boolean;
  /**
   * A list of user IDs of users who are also subscribed to a given stream. Included only if `include_subscribers` is `true`. 
   */
  subscribers?: Array<number>;
  /**
   * A boolean specifying whether desktop notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_desktop_notifications, for this stream. 
   */
  desktop_notifications?: boolean;
  /**
   * A boolean specifying whether email notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_email_notifications, for this stream. 
   */
  email_notifications?: boolean;
  /**
   * A boolean specifying whether wildcard mentions trigger notifications as though they were personal mentions in this stream.  A null value means the value of this setting should be inherited from the user-level default setting, wildcard_mentions_notify, for this stream. 
   */
  wildcard_mentions_notify?: boolean;
  /**
   * A boolean specifying whether push notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_push_notifications, for this stream. 
   */
  push_notifications?: boolean;
  /**
   * A boolean specifying whether audible notifications are enabled for the given stream.  A null value means the value of this setting should be inherited from the user-level default setting, enable_stream_audible_notifications, for this stream. 
   */
  audible_notifications?: boolean;
  /**
   * A boolean specifying whether the given stream has been pinned to the top. 
   */
  pin_to_top?: boolean;
  /**
   * Email address of the given stream, used for [sending emails to the stream](/help/message-a-stream-by-email). 
   */
  email_address?: string;
  /**
   * Whether the user has muted the stream. Muted streams do not count towards your total unread count and do not show up in `All messages` view (previously known as `Home` view).  **Changes**: Prior to Zulip 2.1, this feature was represented by the more confusingly named `in_home_view` (with the opposite value, `in_home_view=!is_muted`). 
   */
  is_muted?: boolean;
  /**
   * Legacy property for if the given stream is muted, with inverted meeting.  **Deprecated**; clients should use is_muted where available. 
   */
  in_home_view?: boolean;
  /**
   * Whether only organization administrators can post to the stream.  **Changes**: Deprecated in Zulip 3.0 (feature level 1), use `stream_post_policy` instead. 
   */
  is_announcement_only?: boolean;
  /**
   * Whether the stream has been configured to allow unauthenticated access to its message history from the web. 
   */
  is_web_public?: boolean;
  /**
   * The user\'s role within the stream (distinct from the user\'s [organization-level role](/help/roles-and-permissions)). Valid values are:  * 20 => Stream administrator. * 50 => Subscriber.  **Changes**: New in Zulip 4.0 (feature level 31). 
   */
  role?: SubscriptionsRoleEnum;
  /**
   * The user\'s personal color for the stream. 
   */
  color?: string;
  /**
   * Policy for which users can post messages to the stream.  * 1 => Any user can post. * 2 => Only administrators can post. * 3 => Only full members can post. * 4 => Only moderators can post.  **Changes**: New in Zulip 3.0, replacing the previous `is_announcement_only` boolean. 
   */
  stream_post_policy?: number;
  /**
   * Number of days that messages sent to this stream will be stored before being automatically deleted by the [message retention policy](/help/message-retention-policy).  There are two special values:  * `null`, the default, means the stream will inherit the organization   level setting. * `-1` encodes retaining messages in this stream forever.  **Changes**: New in Zulip 3.0 (feature level 17). 
   */
  message_retention_days?: number;
  /**
   * Whether the history of the stream is public to its subscribers.  Currently always true for public streams (i.e. invite_only=False implies history_public_to_subscribers=True), but clients should not make that assumption, as we may change that behavior in the future. 
   */
  history_public_to_subscribers?: boolean;
  /**
   * The id of the first message in the stream.  Intended to help clients determine whether they need to display UI like the \"more topics\" widget that would suggest the stream has older history that can be accessed.  Null is used for streams with no message history. 
   */
  first_message_id?: number;
  /**
   * The average number of messages sent to the stream in recent weeks, rounded to the nearest integer.  Null means the stream was recently created and there is insufficient data to estimate the average traffic. 
   */
  stream_weekly_traffic?: number;
}

/**
 * Enum for the role property.
 */
export type SubscriptionsRoleEnum = '20' | '50';


export interface User {
  email?: any;
  is_bot?: any;
  avatar_url?: any;
  avatar_version?: any;
  full_name?: any;
  is_admin?: any;
  is_owner?: any;
  is_billing_admin?: any;
  role?: any;
  bot_type?: any;
  user_id?: any;
  bot_owner_id?: any;
  is_active?: any;
  is_guest?: any;
  timezone?: any;
  date_joined?: any;
  delivery_email?: any;
  profile_data?: any;
}


export interface UserAllOf {
  email?: any;
  is_bot?: any;
  avatar_url?: any;
  avatar_version?: any;
  full_name?: any;
  is_admin?: any;
  is_owner?: any;
  is_billing_admin?: any;
  role?: any;
  bot_type?: any;
  user_id?: any;
  bot_owner_id?: any;
  is_active?: any;
  is_guest?: any;
  timezone?: any;
  date_joined?: any;
  delivery_email?: any;
  profile_data?: any;
}


/**
 * A dictionary containing basic data on a given Zulip user. 
 */
export interface UserBase {
  /**
   * The Zulip API email address of the user or bot.  If you do not have permission to view the email address of the target user, this will be a fake email address that is usable for the Zulip API but nothing else. 
   */
  email?: string;
  /**
   * A boolean specifying whether the user is a bot or full account. 
   */
  is_bot?: boolean;
  /**
   * URL for the user\'s avatar.  Will be `null` if the `client_gravatar` query parameter was set to `True` and the user\'s avatar is hosted by the Gravatar provider (i.e. the user has never uploaded an avatar).  **Changes**: In Zulip 3.0 (feature level 18), if the client has the `user_avatar_url_field_optional` capability, this will be missing at the server\'s sole discretion. 
   */
  avatar_url?: string;
  /**
   * Version for the user\'s avatar.  Used for cache-busting requests for the user\'s avatar.  Clients generally shouldn\'t need to use this; most avatar URLs sent by Zulip will already end with `?v={avatar_version}`. 
   */
  avatar_version?: number;
  /**
   * Full name of the user or bot, used for all display purposes. 
   */
  full_name?: string;
  /**
   * A boolean specifying whether the user is an organization administrator. 
   */
  is_admin?: boolean;
  /**
   * A boolean specifying whether the user is an organization owner. If true, is_admin will also be true.  **Changes**: New in Zulip 3.0 (feature level 8). 
   */
  is_owner?: boolean;
  /**
   * A boolean specifying whether the user is a billing administrator.  **Changes**: New in Zulip 5.0 (feature level 73). 
   */
  is_billing_admin?: boolean;
  /**
   * [Organization-level role](/help/roles-and-permissions)) of the user. Poosible values are:  * Organization owner => 100 * Organization administrator => 200 * Organization moderator => 300 * Member => 400 * Guest => 600  **Changes**: New in Zulip 4.0 (feature level 59). 
   */
  role?: UserBaseRoleEnum;
  /**
   * An integer describing the type of bot: * `null` if the user isn\'t a bot. * `1` for a `Generic` bot. * `2` for an `Incoming webhook` bot. * `3` for an `Outgoing webhook` bot. * `4` for an `Embedded` bot. 
   */
  bot_type?: number;
  /**
   * The unique ID of the user. 
   */
  user_id?: number;
  /**
   * If the user is a bot (i.e. `is_bot` is `True`), `bot_owner` is the user ID of the bot\'s owner (usually, whoever created the bot).  Will be null for legacy bots that do not have an owner.  **Changes**: New in Zulip 3.0 (feature level 1).  In previous versions, there was a `bot_owner` field containing the email address of the bot\'s owner. 
   */
  bot_owner_id?: number;
  /**
   * A boolean specifying whether the user account has been deactivated. 
   */
  is_active?: boolean;
  /**
   * A boolean specifying whether the user is a guest user. 
   */
  is_guest?: boolean;
  /**
   * The time zone of the user. 
   */
  timezone?: string;
  /**
   * The time the user account was created. 
   */
  date_joined?: string;
  /**
   * The user\'s real email address.  This field is present only if [email address visibility](/help/restrict-visibility-of-email-addresses) is limited and you are an administrator with access to real email addresses under the configured policy. 
   */
  delivery_email?: string;
  /**
   * A dictionary containing custom profile field data for the user. Each entry maps the integer ID of a custom profile field in the organization to a dictionary containing the user\'s data for that field.  Generally the data includes just a single `value` key; for those custom profile fields supporting Markdown, a `rendered_value` key will also be present. 
   */
  profile_data?: { [key: string]: object; };
}

/**
 * Enum for the role property.
 */
export type UserBaseRoleEnum = '100' | '200' | '300' | '400' | '600';


export interface UserDeactivatedError {
  result: any;
  msg: any;
  code?: any;
}


/**
 * Object containing the user group\'s attributes. 
 */
export interface UserGroup {
  /**
   * The name of the user group. 
   */
  name?: string;
  /**
   * The description of the user group. 
   */
  description?: string;
  /**
   * Array containing the id of the users who are members of this user group. 
   */
  members?: Array<number>;
  /**
   * The ID of the user group. 
   */
  id?: number;
}


export interface UserNotAuthorizedError {
  result: any;
  msg: any;
  code?: any;
}

