<?php
/**
 * InvalidMessageErrorAllOf
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * InvalidMessageErrorAllOf
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InvalidMessageErrorAllOf
{
    
    /** @var mixed $result */
    private $result;
    
    /** @var mixed $msg */
    private $msg;
    
    /** @var string $rawContent The raw content of the message.*/
    private $rawContent;
}
