/**
 * Zulip REST API
 * Powerful open source group chat 
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIServerAndOrganizationsApiHandler_H
#define OAI_OAIServerAndOrganizationsApiHandler_H

#include <QObject>

#include "OAIHttpFileElement.h"
#include "OAIJsonSuccess.h"
#include "OAIJsonSuccessBase.h"
#include "OAIObject.h"
#include <QString>

namespace OpenAPI {

class OAIServerAndOrganizationsApiHandler : public QObject
{
    Q_OBJECT
    
public:
    OAIServerAndOrganizationsApiHandler();
    virtual ~OAIServerAndOrganizationsApiHandler();


public slots:
    virtual void addCodePlayground(QString name, QString pygments_language, QString url_prefix);
    virtual void addLinkifier(QString pattern, QString url_format_string);
    virtual void createCustomProfileField(qint32 field_type, QString name, QString hint, OAIObject field_data);
    virtual void getCustomEmoji();
    virtual void getCustomProfileFields();
    virtual void getLinkifiers();
    virtual void getServerSettings();
    virtual void removeCodePlayground(qint32 playground_id);
    virtual void removeLinkifier(qint32 filter_id);
    virtual void reorderCustomProfileFields(QList<qint32> order);
    virtual void updateLinkifier(qint32 filter_id, QString pattern, QString url_format_string);
    virtual void uploadCustomEmoji(QString emoji_name, OAIHttpFileElement filename);
    

};

}

#endif // OAI_OAIServerAndOrganizationsApiHandler_H
